// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.N8n.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class AuditVersionGenerated : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The createdAt property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CreatedAt { get; set; }
#nullable restore
#else
        public string CreatedAt { get; set; }
#endif
        /// <summary>The description property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Description { get; set; }
#nullable restore
#else
        public string Description { get; set; }
#endif
        /// <summary>The documentationUrl property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DocumentationUrl { get; set; }
#nullable restore
#else
        public string DocumentationUrl { get; set; }
#endif
        /// <summary>The hasBreakingChange property</summary>
        public bool? HasBreakingChange { get; set; }
        /// <summary>The hasSecurityFix property</summary>
        public bool? HasSecurityFix { get; set; }
        /// <summary>The hasSecurityIssue property</summary>
        public bool? HasSecurityIssue { get; set; }
        /// <summary>The name property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>The nodes property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.N8n.OpenApiClient.Models.AuditVersionGeneratedNodesItem>? Nodes { get; set; }
#nullable restore
#else
        public List<global::Soenneker.N8n.OpenApiClient.Models.AuditVersionGeneratedNodesItem> Nodes { get; set; }
#endif
        /// <summary>The securityIssueFixVersion property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SecurityIssueFixVersion { get; set; }
#nullable restore
#else
        public string SecurityIssueFixVersion { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.N8n.OpenApiClient.Models.AuditVersionGenerated"/> and sets the default values.
        /// </summary>
        public AuditVersionGenerated()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.N8n.OpenApiClient.Models.AuditVersionGenerated"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.N8n.OpenApiClient.Models.AuditVersionGenerated CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.N8n.OpenApiClient.Models.AuditVersionGenerated();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "createdAt", n => { CreatedAt = n.GetStringValue(); } },
                { "description", n => { Description = n.GetStringValue(); } },
                { "documentationUrl", n => { DocumentationUrl = n.GetStringValue(); } },
                { "hasBreakingChange", n => { HasBreakingChange = n.GetBoolValue(); } },
                { "hasSecurityFix", n => { HasSecurityFix = n.GetBoolValue(); } },
                { "hasSecurityIssue", n => { HasSecurityIssue = n.GetBoolValue(); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "nodes", n => { Nodes = n.GetCollectionOfObjectValues<global::Soenneker.N8n.OpenApiClient.Models.AuditVersionGeneratedNodesItem>(global::Soenneker.N8n.OpenApiClient.Models.AuditVersionGeneratedNodesItem.CreateFromDiscriminatorValue)?.AsList(); } },
                { "securityIssueFixVersion", n => { SecurityIssueFixVersion = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("createdAt", CreatedAt);
            writer.WriteStringValue("description", Description);
            writer.WriteStringValue("documentationUrl", DocumentationUrl);
            writer.WriteBoolValue("hasBreakingChange", HasBreakingChange);
            writer.WriteBoolValue("hasSecurityFix", HasSecurityFix);
            writer.WriteBoolValue("hasSecurityIssue", HasSecurityIssue);
            writer.WriteStringValue("name", Name);
            writer.WriteCollectionOfObjectValues<global::Soenneker.N8n.OpenApiClient.Models.AuditVersionGeneratedNodesItem>("nodes", Nodes);
            writer.WriteStringValue("securityIssueFixVersion", SecurityIssueFixVersion);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
