// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.N8n.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum CreateUserRequestItemRoleAnyOf1
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "global:admin")]
        #pragma warning disable CS1591
        GlobalColonAdmin,
        #pragma warning restore CS1591
        [EnumMember(Value = "global:member")]
        #pragma warning disable CS1591
        GlobalColonMember,
        #pragma warning restore CS1591
        [EnumMember(Value = "global:chatUser")]
        #pragma warning disable CS1591
        GlobalColonChatUser,
        #pragma warning restore CS1591
    }
}
