// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.N8n.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class CreatePromotionConnectionRequest : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The configs property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.N8n.OpenApiClient.Models.CreatePromotionConnectionRequestConfigs? Configs { get; set; }
#nullable restore
#else
        public global::Soenneker.N8n.OpenApiClient.Models.CreatePromotionConnectionRequestConfigs Configs { get; set; }
#endif
        /// <summary>The name property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>The providerId property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ProviderId { get; set; }
#nullable restore
#else
        public string ProviderId { get; set; }
#endif
        /// <summary>The scope property</summary>
        public global::Soenneker.N8n.OpenApiClient.Models.CreatePromotionConnectionRequestScope? Scope { get; set; }
        /// <summary>The target property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.N8n.OpenApiClient.Models.CreatePromotionConnectionRequestTarget? Target { get; set; }
#nullable restore
#else
        public global::Soenneker.N8n.OpenApiClient.Models.CreatePromotionConnectionRequestTarget Target { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.N8n.OpenApiClient.Models.CreatePromotionConnectionRequest"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.N8n.OpenApiClient.Models.CreatePromotionConnectionRequest CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.N8n.OpenApiClient.Models.CreatePromotionConnectionRequest();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "configs", n => { Configs = n.GetObjectValue<global::Soenneker.N8n.OpenApiClient.Models.CreatePromotionConnectionRequestConfigs>(global::Soenneker.N8n.OpenApiClient.Models.CreatePromotionConnectionRequestConfigs.CreateFromDiscriminatorValue); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "providerId", n => { ProviderId = n.GetStringValue(); } },
                { "scope", n => { Scope = n.GetEnumValue<global::Soenneker.N8n.OpenApiClient.Models.CreatePromotionConnectionRequestScope>(); } },
                { "target", n => { Target = n.GetObjectValue<global::Soenneker.N8n.OpenApiClient.Models.CreatePromotionConnectionRequestTarget>(global::Soenneker.N8n.OpenApiClient.Models.CreatePromotionConnectionRequestTarget.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Soenneker.N8n.OpenApiClient.Models.CreatePromotionConnectionRequestConfigs>("configs", Configs);
            writer.WriteStringValue("name", Name);
            writer.WriteStringValue("providerId", ProviderId);
            writer.WriteEnumValue<global::Soenneker.N8n.OpenApiClient.Models.CreatePromotionConnectionRequestScope>("scope", Scope);
            writer.WriteObjectValue<global::Soenneker.N8n.OpenApiClient.Models.CreatePromotionConnectionRequestTarget>("target", Target);
        }
    }
}
#pragma warning restore CS0618
