// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.N8n.OpenApiClient.Models
{
    /// <summary>
    /// Execution and behaviour settings for the workflow
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class CreateWorkflow200ResponseSettings : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Controls whether this workflow is reachable over the Model Context Protocol (MCP). Defaults to false. The workflow must be active and must hold at least one active Webhook node.</summary>
        public bool? AvailableInMCP { get; set; }
        /// <summary>Controls how binary data is resolved from a node&apos;s input. This is a derived, internal setting rather than something intended to be set programmatically. It is included in workflow responses for reference, but any value sent when creating or updating a workflow is ignored.</summary>
        public global::Soenneker.N8n.OpenApiClient.Models.CreateWorkflow200ResponseSettingsBinaryMode? BinaryMode { get; set; }
        /// <summary>Comma-separated list of workflow IDs allowed to call this workflow (only used with the workflowsFromAList policy)</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CallerIds { get; set; }
#nullable restore
#else
        public string CallerIds { get; set; }
#endif
        /// <summary>Controls which workflows are allowed to call this workflow using the Execute Workflow node. Defaults to workflowsFromSameOwner.Available options:- `any`: Any workflow can call this workflow (no restrictions)- `none`: No other workflows can call this workflow (completely blocked)- `workflowsFromSameOwner` (default): Only workflows owned by the same project can call this workflow- `workflowsFromAList`: Only the workflows listed in `callerIds` can call this workflow</summary>
        public global::Soenneker.N8n.OpenApiClient.Models.CreateWorkflow200ResponseSettingsCallerPolicy? CallerPolicy { get; set; }
        /// <summary>ID of the credential resolver that resolves credentials for this workflow. This is a derived, internal setting managed through the credential resolver configuration rather than something intended to be set programmatically. It is included in workflow responses for reference, but any value sent when creating or updating a workflow is ignored.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CredentialResolverId { get; set; }
#nullable restore
#else
        public string CredentialResolverId { get; set; }
#endif
        /// <summary>The customTelemetryTags property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.N8n.OpenApiClient.Models.CreateWorkflow200ResponseSettingsCustomTelemetryTagsItem>? CustomTelemetryTags { get; set; }
#nullable restore
#else
        public List<global::Soenneker.N8n.OpenApiClient.Models.CreateWorkflow200ResponseSettingsCustomTelemetryTagsItem> CustomTelemetryTags { get; set; }
#endif
        /// <summary>The ID of the workflow that contains the error trigger node.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ErrorWorkflow { get; set; }
#nullable restore
#else
        public string ErrorWorkflow { get; set; }
#endif
        /// <summary>The executionOrder property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ExecutionOrder { get; set; }
#nullable restore
#else
        public string ExecutionOrder { get; set; }
#endif
        /// <summary>The executionTimeout property</summary>
        public double? ExecutionTimeout { get; set; }
        /// <summary>Controls whether execution data is redacted for this workflow.Available options:- `none` (default): No redaction. All execution data is stored.- `non-manual`: Redact production (non-manually triggered) executions only.- `manual-only`: Redact manually triggered executions only.- `all`: Redact all executions, manual and production.</summary>
        public global::Soenneker.N8n.OpenApiClient.Models.CreateWorkflow200ResponseSettingsRedactionPolicy? RedactionPolicy { get; set; }
        /// <summary>The saveDataErrorExecution property</summary>
        public global::Soenneker.N8n.OpenApiClient.Models.CreateWorkflow200ResponseSettingsSaveDataErrorExecution? SaveDataErrorExecution { get; set; }
        /// <summary>The saveDataSuccessExecution property</summary>
        public global::Soenneker.N8n.OpenApiClient.Models.CreateWorkflow200ResponseSettingsSaveDataSuccessExecution? SaveDataSuccessExecution { get; set; }
        /// <summary>The saveExecutionProgress property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.N8n.OpenApiClient.Models.CreateWorkflow200ResponseSettingsSaveExecutionProgress? SaveExecutionProgress { get; set; }
#nullable restore
#else
        public global::Soenneker.N8n.OpenApiClient.Models.CreateWorkflow200ResponseSettingsSaveExecutionProgress SaveExecutionProgress { get; set; }
#endif
        /// <summary>The saveManualExecutions property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.N8n.OpenApiClient.Models.CreateWorkflow200ResponseSettingsSaveManualExecutions? SaveManualExecutions { get; set; }
#nullable restore
#else
        public global::Soenneker.N8n.OpenApiClient.Models.CreateWorkflow200ResponseSettingsSaveManualExecutions SaveManualExecutions { get; set; }
#endif
        /// <summary>Controls how the time saved per execution is calculated.Available options:- `fixed`: Uses the value in `timeSavedPerExecution`. Use when the time saved is the same for every execution.- `dynamic`: Calculates the time saved from actual execution metrics. `timeSavedPerExecution` is ignored.</summary>
        public global::Soenneker.N8n.OpenApiClient.Models.CreateWorkflow200ResponseSettingsTimeSavedMode? TimeSavedMode { get; set; }
        /// <summary>Estimated time saved per execution in minutes</summary>
        public double? TimeSavedPerExecution { get; set; }
        /// <summary>The timezone property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Timezone { get; set; }
#nullable restore
#else
        public string Timezone { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.N8n.OpenApiClient.Models.CreateWorkflow200ResponseSettings"/> and sets the default values.
        /// </summary>
        public CreateWorkflow200ResponseSettings()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.N8n.OpenApiClient.Models.CreateWorkflow200ResponseSettings"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.N8n.OpenApiClient.Models.CreateWorkflow200ResponseSettings CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.N8n.OpenApiClient.Models.CreateWorkflow200ResponseSettings();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "availableInMCP", n => { AvailableInMCP = n.GetBoolValue(); } },
                { "binaryMode", n => { BinaryMode = n.GetEnumValue<global::Soenneker.N8n.OpenApiClient.Models.CreateWorkflow200ResponseSettingsBinaryMode>(); } },
                { "callerIds", n => { CallerIds = n.GetStringValue(); } },
                { "callerPolicy", n => { CallerPolicy = n.GetEnumValue<global::Soenneker.N8n.OpenApiClient.Models.CreateWorkflow200ResponseSettingsCallerPolicy>(); } },
                { "credentialResolverId", n => { CredentialResolverId = n.GetStringValue(); } },
                { "customTelemetryTags", n => { CustomTelemetryTags = n.GetCollectionOfObjectValues<global::Soenneker.N8n.OpenApiClient.Models.CreateWorkflow200ResponseSettingsCustomTelemetryTagsItem>(global::Soenneker.N8n.OpenApiClient.Models.CreateWorkflow200ResponseSettingsCustomTelemetryTagsItem.CreateFromDiscriminatorValue)?.AsList(); } },
                { "errorWorkflow", n => { ErrorWorkflow = n.GetStringValue(); } },
                { "executionOrder", n => { ExecutionOrder = n.GetStringValue(); } },
                { "executionTimeout", n => { ExecutionTimeout = n.GetDoubleValue(); } },
                { "redactionPolicy", n => { RedactionPolicy = n.GetEnumValue<global::Soenneker.N8n.OpenApiClient.Models.CreateWorkflow200ResponseSettingsRedactionPolicy>(); } },
                { "saveDataErrorExecution", n => { SaveDataErrorExecution = n.GetEnumValue<global::Soenneker.N8n.OpenApiClient.Models.CreateWorkflow200ResponseSettingsSaveDataErrorExecution>(); } },
                { "saveDataSuccessExecution", n => { SaveDataSuccessExecution = n.GetEnumValue<global::Soenneker.N8n.OpenApiClient.Models.CreateWorkflow200ResponseSettingsSaveDataSuccessExecution>(); } },
                { "saveExecutionProgress", n => { SaveExecutionProgress = n.GetObjectValue<global::Soenneker.N8n.OpenApiClient.Models.CreateWorkflow200ResponseSettingsSaveExecutionProgress>(global::Soenneker.N8n.OpenApiClient.Models.CreateWorkflow200ResponseSettingsSaveExecutionProgress.CreateFromDiscriminatorValue); } },
                { "saveManualExecutions", n => { SaveManualExecutions = n.GetObjectValue<global::Soenneker.N8n.OpenApiClient.Models.CreateWorkflow200ResponseSettingsSaveManualExecutions>(global::Soenneker.N8n.OpenApiClient.Models.CreateWorkflow200ResponseSettingsSaveManualExecutions.CreateFromDiscriminatorValue); } },
                { "timeSavedMode", n => { TimeSavedMode = n.GetEnumValue<global::Soenneker.N8n.OpenApiClient.Models.CreateWorkflow200ResponseSettingsTimeSavedMode>(); } },
                { "timeSavedPerExecution", n => { TimeSavedPerExecution = n.GetDoubleValue(); } },
                { "timezone", n => { Timezone = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteBoolValue("availableInMCP", AvailableInMCP);
            writer.WriteEnumValue<global::Soenneker.N8n.OpenApiClient.Models.CreateWorkflow200ResponseSettingsBinaryMode>("binaryMode", BinaryMode);
            writer.WriteStringValue("callerIds", CallerIds);
            writer.WriteEnumValue<global::Soenneker.N8n.OpenApiClient.Models.CreateWorkflow200ResponseSettingsCallerPolicy>("callerPolicy", CallerPolicy);
            writer.WriteStringValue("credentialResolverId", CredentialResolverId);
            writer.WriteCollectionOfObjectValues<global::Soenneker.N8n.OpenApiClient.Models.CreateWorkflow200ResponseSettingsCustomTelemetryTagsItem>("customTelemetryTags", CustomTelemetryTags);
            writer.WriteStringValue("errorWorkflow", ErrorWorkflow);
            writer.WriteStringValue("executionOrder", ExecutionOrder);
            writer.WriteDoubleValue("executionTimeout", ExecutionTimeout);
            writer.WriteEnumValue<global::Soenneker.N8n.OpenApiClient.Models.CreateWorkflow200ResponseSettingsRedactionPolicy>("redactionPolicy", RedactionPolicy);
            writer.WriteEnumValue<global::Soenneker.N8n.OpenApiClient.Models.CreateWorkflow200ResponseSettingsSaveDataErrorExecution>("saveDataErrorExecution", SaveDataErrorExecution);
            writer.WriteEnumValue<global::Soenneker.N8n.OpenApiClient.Models.CreateWorkflow200ResponseSettingsSaveDataSuccessExecution>("saveDataSuccessExecution", SaveDataSuccessExecution);
            writer.WriteObjectValue<global::Soenneker.N8n.OpenApiClient.Models.CreateWorkflow200ResponseSettingsSaveExecutionProgress>("saveExecutionProgress", SaveExecutionProgress);
            writer.WriteObjectValue<global::Soenneker.N8n.OpenApiClient.Models.CreateWorkflow200ResponseSettingsSaveManualExecutions>("saveManualExecutions", SaveManualExecutions);
            writer.WriteEnumValue<global::Soenneker.N8n.OpenApiClient.Models.CreateWorkflow200ResponseSettingsTimeSavedMode>("timeSavedMode", TimeSavedMode);
            writer.WriteDoubleValue("timeSavedPerExecution", TimeSavedPerExecution);
            writer.WriteStringValue("timezone", Timezone);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
