// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.N8n.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum Execution_mode
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "cli")]
        #pragma warning disable CS1591
        Cli,
        #pragma warning restore CS1591
        [EnumMember(Value = "error")]
        #pragma warning disable CS1591
        Error,
        #pragma warning restore CS1591
        [EnumMember(Value = "integrated")]
        #pragma warning disable CS1591
        Integrated,
        #pragma warning restore CS1591
        [EnumMember(Value = "internal")]
        #pragma warning disable CS1591
        Internal,
        #pragma warning restore CS1591
        [EnumMember(Value = "manual")]
        #pragma warning disable CS1591
        Manual,
        #pragma warning restore CS1591
        [EnumMember(Value = "retry")]
        #pragma warning disable CS1591
        Retry,
        #pragma warning restore CS1591
        [EnumMember(Value = "trigger")]
        #pragma warning disable CS1591
        Trigger,
        #pragma warning restore CS1591
        [EnumMember(Value = "webhook")]
        #pragma warning disable CS1591
        Webhook,
        #pragma warning restore CS1591
        [EnumMember(Value = "evaluation")]
        #pragma warning disable CS1591
        Evaluation,
        #pragma warning restore CS1591
        [EnumMember(Value = "chat")]
        #pragma warning disable CS1591
        Chat,
        #pragma warning restore CS1591
    }
}
