// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.N8n.OpenApiClient.Models
{
    /// <summary>Policy for missing static sub-workflow dependencies. `fail` aborts the export when any static sub-workflow is missing from the package; `include-in-package` automatically adds missing static sub-workflows. `reference-only` keeps missing static sub-workflows out of the package and lists them in the package requirements as workflows expected to already exist on the target.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum ExportPackageRequestMissingWorkflowDependencyPolicy
    {
        [EnumMember(Value = "fail")]
        #pragma warning disable CS1591
        Fail,
        #pragma warning restore CS1591
        [EnumMember(Value = "reference-only")]
        #pragma warning disable CS1591
        ReferenceOnly,
        #pragma warning restore CS1591
        [EnumMember(Value = "include-in-package")]
        #pragma warning disable CS1591
        IncludeInPackage,
        #pragma warning restore CS1591
    }
}
