// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.N8n.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class GenerateAudit200ResponseAnyOf1 : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The CredentialsRiskReport property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.N8n.OpenApiClient.Models.GenerateAudit200ResponseAnyOf1CredentialsRiskReport? CredentialsRiskReport { get; set; }
#nullable restore
#else
        public global::Soenneker.N8n.OpenApiClient.Models.GenerateAudit200ResponseAnyOf1CredentialsRiskReport CredentialsRiskReport { get; set; }
#endif
        /// <summary>The DatabaseRiskReport property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.N8n.OpenApiClient.Models.GenerateAudit200ResponseAnyOf1DatabaseRiskReport? DatabaseRiskReport { get; set; }
#nullable restore
#else
        public global::Soenneker.N8n.OpenApiClient.Models.GenerateAudit200ResponseAnyOf1DatabaseRiskReport DatabaseRiskReport { get; set; }
#endif
        /// <summary>The FilesystemRiskReport property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.N8n.OpenApiClient.Models.GenerateAudit200ResponseAnyOf1FilesystemRiskReport? FilesystemRiskReport { get; set; }
#nullable restore
#else
        public global::Soenneker.N8n.OpenApiClient.Models.GenerateAudit200ResponseAnyOf1FilesystemRiskReport FilesystemRiskReport { get; set; }
#endif
        /// <summary>The InstanceRiskReport property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.N8n.OpenApiClient.Models.GenerateAudit200ResponseAnyOf1InstanceRiskReport? InstanceRiskReport { get; set; }
#nullable restore
#else
        public global::Soenneker.N8n.OpenApiClient.Models.GenerateAudit200ResponseAnyOf1InstanceRiskReport InstanceRiskReport { get; set; }
#endif
        /// <summary>The NodesRiskReport property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.N8n.OpenApiClient.Models.GenerateAudit200ResponseAnyOf1NodesRiskReport? NodesRiskReport { get; set; }
#nullable restore
#else
        public global::Soenneker.N8n.OpenApiClient.Models.GenerateAudit200ResponseAnyOf1NodesRiskReport NodesRiskReport { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.N8n.OpenApiClient.Models.GenerateAudit200ResponseAnyOf1"/> and sets the default values.
        /// </summary>
        public GenerateAudit200ResponseAnyOf1()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.N8n.OpenApiClient.Models.GenerateAudit200ResponseAnyOf1"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.N8n.OpenApiClient.Models.GenerateAudit200ResponseAnyOf1 CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.N8n.OpenApiClient.Models.GenerateAudit200ResponseAnyOf1();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "Credentials Risk Report", n => { CredentialsRiskReport = n.GetObjectValue<global::Soenneker.N8n.OpenApiClient.Models.GenerateAudit200ResponseAnyOf1CredentialsRiskReport>(global::Soenneker.N8n.OpenApiClient.Models.GenerateAudit200ResponseAnyOf1CredentialsRiskReport.CreateFromDiscriminatorValue); } },
                { "Database Risk Report", n => { DatabaseRiskReport = n.GetObjectValue<global::Soenneker.N8n.OpenApiClient.Models.GenerateAudit200ResponseAnyOf1DatabaseRiskReport>(global::Soenneker.N8n.OpenApiClient.Models.GenerateAudit200ResponseAnyOf1DatabaseRiskReport.CreateFromDiscriminatorValue); } },
                { "Filesystem Risk Report", n => { FilesystemRiskReport = n.GetObjectValue<global::Soenneker.N8n.OpenApiClient.Models.GenerateAudit200ResponseAnyOf1FilesystemRiskReport>(global::Soenneker.N8n.OpenApiClient.Models.GenerateAudit200ResponseAnyOf1FilesystemRiskReport.CreateFromDiscriminatorValue); } },
                { "Instance Risk Report", n => { InstanceRiskReport = n.GetObjectValue<global::Soenneker.N8n.OpenApiClient.Models.GenerateAudit200ResponseAnyOf1InstanceRiskReport>(global::Soenneker.N8n.OpenApiClient.Models.GenerateAudit200ResponseAnyOf1InstanceRiskReport.CreateFromDiscriminatorValue); } },
                { "Nodes Risk Report", n => { NodesRiskReport = n.GetObjectValue<global::Soenneker.N8n.OpenApiClient.Models.GenerateAudit200ResponseAnyOf1NodesRiskReport>(global::Soenneker.N8n.OpenApiClient.Models.GenerateAudit200ResponseAnyOf1NodesRiskReport.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Soenneker.N8n.OpenApiClient.Models.GenerateAudit200ResponseAnyOf1CredentialsRiskReport>("Credentials Risk Report", CredentialsRiskReport);
            writer.WriteObjectValue<global::Soenneker.N8n.OpenApiClient.Models.GenerateAudit200ResponseAnyOf1DatabaseRiskReport>("Database Risk Report", DatabaseRiskReport);
            writer.WriteObjectValue<global::Soenneker.N8n.OpenApiClient.Models.GenerateAudit200ResponseAnyOf1FilesystemRiskReport>("Filesystem Risk Report", FilesystemRiskReport);
            writer.WriteObjectValue<global::Soenneker.N8n.OpenApiClient.Models.GenerateAudit200ResponseAnyOf1InstanceRiskReport>("Instance Risk Report", InstanceRiskReport);
            writer.WriteObjectValue<global::Soenneker.N8n.OpenApiClient.Models.GenerateAudit200ResponseAnyOf1NodesRiskReport>("Nodes Risk Report", NodesRiskReport);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
