// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.N8n.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class GenerateAudit200ResponseAnyOf1FilesystemRiskReportSectionsItemLocationItem : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The filePath property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? FilePath { get; set; }
#nullable restore
#else
        public string FilePath { get; set; }
#endif
        /// <summary>The id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Id { get; set; }
#nullable restore
#else
        public string Id { get; set; }
#endif
        /// <summary>The kind property</summary>
        public global::Soenneker.N8n.OpenApiClient.Models.GenerateAudit200ResponseAnyOf1FilesystemRiskReportSectionsItemLocationItemKind? Kind { get; set; }
        /// <summary>The name property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>The nodeId property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? NodeId { get; set; }
#nullable restore
#else
        public string NodeId { get; set; }
#endif
        /// <summary>The nodeName property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? NodeName { get; set; }
#nullable restore
#else
        public string NodeName { get; set; }
#endif
        /// <summary>The nodeType property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? NodeType { get; set; }
#nullable restore
#else
        public string NodeType { get; set; }
#endif
        /// <summary>The packageUrl property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PackageUrl { get; set; }
#nullable restore
#else
        public string PackageUrl { get; set; }
#endif
        /// <summary>The workflowId property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? WorkflowId { get; set; }
#nullable restore
#else
        public string WorkflowId { get; set; }
#endif
        /// <summary>The workflowName property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? WorkflowName { get; set; }
#nullable restore
#else
        public string WorkflowName { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.N8n.OpenApiClient.Models.GenerateAudit200ResponseAnyOf1FilesystemRiskReportSectionsItemLocationItem"/> and sets the default values.
        /// </summary>
        public GenerateAudit200ResponseAnyOf1FilesystemRiskReportSectionsItemLocationItem()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.N8n.OpenApiClient.Models.GenerateAudit200ResponseAnyOf1FilesystemRiskReportSectionsItemLocationItem"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.N8n.OpenApiClient.Models.GenerateAudit200ResponseAnyOf1FilesystemRiskReportSectionsItemLocationItem CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.N8n.OpenApiClient.Models.GenerateAudit200ResponseAnyOf1FilesystemRiskReportSectionsItemLocationItem();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "filePath", n => { FilePath = n.GetStringValue(); } },
                { "id", n => { Id = n.GetStringValue(); } },
                { "kind", n => { Kind = n.GetEnumValue<global::Soenneker.N8n.OpenApiClient.Models.GenerateAudit200ResponseAnyOf1FilesystemRiskReportSectionsItemLocationItemKind>(); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "nodeId", n => { NodeId = n.GetStringValue(); } },
                { "nodeName", n => { NodeName = n.GetStringValue(); } },
                { "nodeType", n => { NodeType = n.GetStringValue(); } },
                { "packageUrl", n => { PackageUrl = n.GetStringValue(); } },
                { "workflowId", n => { WorkflowId = n.GetStringValue(); } },
                { "workflowName", n => { WorkflowName = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("filePath", FilePath);
            writer.WriteStringValue("id", Id);
            writer.WriteEnumValue<global::Soenneker.N8n.OpenApiClient.Models.GenerateAudit200ResponseAnyOf1FilesystemRiskReportSectionsItemLocationItemKind>("kind", Kind);
            writer.WriteStringValue("name", Name);
            writer.WriteStringValue("nodeId", NodeId);
            writer.WriteStringValue("nodeName", NodeName);
            writer.WriteStringValue("nodeType", NodeType);
            writer.WriteStringValue("packageUrl", PackageUrl);
            writer.WriteStringValue("workflowId", WorkflowId);
            writer.WriteStringValue("workflowName", WorkflowName);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
