// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.N8n.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class GetTestCases200ResponseDataItem : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The completedAt property</summary>
        public DateTimeOffset? CompletedAt { get; set; }
        /// <summary>The errorCode property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ErrorCode { get; set; }
#nullable restore
#else
        public string ErrorCode { get; set; }
#endif
        /// <summary>The errorDetails property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.N8n.OpenApiClient.Models.GetTestCases200ResponseDataItemErrorDetails? ErrorDetails { get; set; }
#nullable restore
#else
        public global::Soenneker.N8n.OpenApiClient.Models.GetTestCases200ResponseDataItemErrorDetails ErrorDetails { get; set; }
#endif
        /// <summary>ID of the underlying workflow execution, if still retained.</summary>
        public int? ExecutionId { get; set; }
        /// <summary>The id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Id { get; set; }
#nullable restore
#else
        public string Id { get; set; }
#endif
        /// <summary>Input data for this test case.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.N8n.OpenApiClient.Models.GetTestCases200ResponseDataItemInputs? Inputs { get; set; }
#nullable restore
#else
        public global::Soenneker.N8n.OpenApiClient.Models.GetTestCases200ResponseDataItemInputs Inputs { get; set; }
#endif
        /// <summary>Metrics produced by this test case.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.N8n.OpenApiClient.Models.GetTestCases200ResponseDataItemMetrics? Metrics { get; set; }
#nullable restore
#else
        public global::Soenneker.N8n.OpenApiClient.Models.GetTestCases200ResponseDataItemMetrics Metrics { get; set; }
#endif
        /// <summary>Output data produced by this test case.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.N8n.OpenApiClient.Models.GetTestCases200ResponseDataItemOutputs? Outputs { get; set; }
#nullable restore
#else
        public global::Soenneker.N8n.OpenApiClient.Models.GetTestCases200ResponseDataItemOutputs Outputs { get; set; }
#endif
        /// <summary>The runAt property</summary>
        public DateTimeOffset? RunAt { get; set; }
        /// <summary>The status property</summary>
        public global::Soenneker.N8n.OpenApiClient.Models.GetTestCases200ResponseDataItemStatus? Status { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.N8n.OpenApiClient.Models.GetTestCases200ResponseDataItem"/> and sets the default values.
        /// </summary>
        public GetTestCases200ResponseDataItem()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.N8n.OpenApiClient.Models.GetTestCases200ResponseDataItem"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.N8n.OpenApiClient.Models.GetTestCases200ResponseDataItem CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.N8n.OpenApiClient.Models.GetTestCases200ResponseDataItem();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "completedAt", n => { CompletedAt = n.GetDateTimeOffsetValue(); } },
                { "errorCode", n => { ErrorCode = n.GetStringValue(); } },
                { "errorDetails", n => { ErrorDetails = n.GetObjectValue<global::Soenneker.N8n.OpenApiClient.Models.GetTestCases200ResponseDataItemErrorDetails>(global::Soenneker.N8n.OpenApiClient.Models.GetTestCases200ResponseDataItemErrorDetails.CreateFromDiscriminatorValue); } },
                { "executionId", n => { ExecutionId = n.GetIntValue(); } },
                { "id", n => { Id = n.GetStringValue(); } },
                { "inputs", n => { Inputs = n.GetObjectValue<global::Soenneker.N8n.OpenApiClient.Models.GetTestCases200ResponseDataItemInputs>(global::Soenneker.N8n.OpenApiClient.Models.GetTestCases200ResponseDataItemInputs.CreateFromDiscriminatorValue); } },
                { "metrics", n => { Metrics = n.GetObjectValue<global::Soenneker.N8n.OpenApiClient.Models.GetTestCases200ResponseDataItemMetrics>(global::Soenneker.N8n.OpenApiClient.Models.GetTestCases200ResponseDataItemMetrics.CreateFromDiscriminatorValue); } },
                { "outputs", n => { Outputs = n.GetObjectValue<global::Soenneker.N8n.OpenApiClient.Models.GetTestCases200ResponseDataItemOutputs>(global::Soenneker.N8n.OpenApiClient.Models.GetTestCases200ResponseDataItemOutputs.CreateFromDiscriminatorValue); } },
                { "runAt", n => { RunAt = n.GetDateTimeOffsetValue(); } },
                { "status", n => { Status = n.GetEnumValue<global::Soenneker.N8n.OpenApiClient.Models.GetTestCases200ResponseDataItemStatus>(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteDateTimeOffsetValue("completedAt", CompletedAt);
            writer.WriteStringValue("errorCode", ErrorCode);
            writer.WriteObjectValue<global::Soenneker.N8n.OpenApiClient.Models.GetTestCases200ResponseDataItemErrorDetails>("errorDetails", ErrorDetails);
            writer.WriteIntValue("executionId", ExecutionId);
            writer.WriteStringValue("id", Id);
            writer.WriteObjectValue<global::Soenneker.N8n.OpenApiClient.Models.GetTestCases200ResponseDataItemInputs>("inputs", Inputs);
            writer.WriteObjectValue<global::Soenneker.N8n.OpenApiClient.Models.GetTestCases200ResponseDataItemMetrics>("metrics", Metrics);
            writer.WriteObjectValue<global::Soenneker.N8n.OpenApiClient.Models.GetTestCases200ResponseDataItemOutputs>("outputs", Outputs);
            writer.WriteDateTimeOffsetValue("runAt", RunAt);
            writer.WriteEnumValue<global::Soenneker.N8n.OpenApiClient.Models.GetTestCases200ResponseDataItemStatus>("status", Status);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
