// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.N8n.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class GetWorkflow200ResponseActiveVersion : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The authors property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Authors { get; set; }
#nullable restore
#else
        public string Authors { get; set; }
#endif
        /// <summary>The autosaved property</summary>
        public bool? Autosaved { get; set; }
        /// <summary>The connections property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.N8n.OpenApiClient.Models.GetWorkflow200ResponseActiveVersionConnections? Connections { get; set; }
#nullable restore
#else
        public global::Soenneker.N8n.OpenApiClient.Models.GetWorkflow200ResponseActiveVersionConnections Connections { get; set; }
#endif
        /// <summary>The createdAt property</summary>
        public DateTimeOffset? CreatedAt { get; set; }
        /// <summary>The description property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Description { get; set; }
#nullable restore
#else
        public string Description { get; set; }
#endif
        /// <summary>The name property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>The nodeGroups property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.N8n.OpenApiClient.Models.GetWorkflow200ResponseActiveVersionNodeGroups? NodeGroups { get; set; }
#nullable restore
#else
        public global::Soenneker.N8n.OpenApiClient.Models.GetWorkflow200ResponseActiveVersionNodeGroups NodeGroups { get; set; }
#endif
        /// <summary>The nodes property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.N8n.OpenApiClient.Models.GetWorkflow200ResponseActiveVersionNodes? Nodes { get; set; }
#nullable restore
#else
        public global::Soenneker.N8n.OpenApiClient.Models.GetWorkflow200ResponseActiveVersionNodes Nodes { get; set; }
#endif
        /// <summary>The updatedAt property</summary>
        public DateTimeOffset? UpdatedAt { get; set; }
        /// <summary>The versionId property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? VersionId { get; set; }
#nullable restore
#else
        public string VersionId { get; set; }
#endif
        /// <summary>The workflowId property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? WorkflowId { get; set; }
#nullable restore
#else
        public string WorkflowId { get; set; }
#endif
        /// <summary>The workflowPublishHistory property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.N8n.OpenApiClient.Models.GetWorkflow200ResponseActiveVersionWorkflowPublishHistoryItem>? WorkflowPublishHistory { get; set; }
#nullable restore
#else
        public List<global::Soenneker.N8n.OpenApiClient.Models.GetWorkflow200ResponseActiveVersionWorkflowPublishHistoryItem> WorkflowPublishHistory { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.N8n.OpenApiClient.Models.GetWorkflow200ResponseActiveVersion"/> and sets the default values.
        /// </summary>
        public GetWorkflow200ResponseActiveVersion()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.N8n.OpenApiClient.Models.GetWorkflow200ResponseActiveVersion"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.N8n.OpenApiClient.Models.GetWorkflow200ResponseActiveVersion CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.N8n.OpenApiClient.Models.GetWorkflow200ResponseActiveVersion();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "authors", n => { Authors = n.GetStringValue(); } },
                { "autosaved", n => { Autosaved = n.GetBoolValue(); } },
                { "connections", n => { Connections = n.GetObjectValue<global::Soenneker.N8n.OpenApiClient.Models.GetWorkflow200ResponseActiveVersionConnections>(global::Soenneker.N8n.OpenApiClient.Models.GetWorkflow200ResponseActiveVersionConnections.CreateFromDiscriminatorValue); } },
                { "createdAt", n => { CreatedAt = n.GetDateTimeOffsetValue(); } },
                { "description", n => { Description = n.GetStringValue(); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "nodeGroups", n => { NodeGroups = n.GetObjectValue<global::Soenneker.N8n.OpenApiClient.Models.GetWorkflow200ResponseActiveVersionNodeGroups>(global::Soenneker.N8n.OpenApiClient.Models.GetWorkflow200ResponseActiveVersionNodeGroups.CreateFromDiscriminatorValue); } },
                { "nodes", n => { Nodes = n.GetObjectValue<global::Soenneker.N8n.OpenApiClient.Models.GetWorkflow200ResponseActiveVersionNodes>(global::Soenneker.N8n.OpenApiClient.Models.GetWorkflow200ResponseActiveVersionNodes.CreateFromDiscriminatorValue); } },
                { "updatedAt", n => { UpdatedAt = n.GetDateTimeOffsetValue(); } },
                { "versionId", n => { VersionId = n.GetStringValue(); } },
                { "workflowId", n => { WorkflowId = n.GetStringValue(); } },
                { "workflowPublishHistory", n => { WorkflowPublishHistory = n.GetCollectionOfObjectValues<global::Soenneker.N8n.OpenApiClient.Models.GetWorkflow200ResponseActiveVersionWorkflowPublishHistoryItem>(global::Soenneker.N8n.OpenApiClient.Models.GetWorkflow200ResponseActiveVersionWorkflowPublishHistoryItem.CreateFromDiscriminatorValue)?.AsList(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("authors", Authors);
            writer.WriteBoolValue("autosaved", Autosaved);
            writer.WriteObjectValue<global::Soenneker.N8n.OpenApiClient.Models.GetWorkflow200ResponseActiveVersionConnections>("connections", Connections);
            writer.WriteDateTimeOffsetValue("createdAt", CreatedAt);
            writer.WriteStringValue("description", Description);
            writer.WriteStringValue("name", Name);
            writer.WriteObjectValue<global::Soenneker.N8n.OpenApiClient.Models.GetWorkflow200ResponseActiveVersionNodeGroups>("nodeGroups", NodeGroups);
            writer.WriteObjectValue<global::Soenneker.N8n.OpenApiClient.Models.GetWorkflow200ResponseActiveVersionNodes>("nodes", Nodes);
            writer.WriteDateTimeOffsetValue("updatedAt", UpdatedAt);
            writer.WriteStringValue("versionId", VersionId);
            writer.WriteStringValue("workflowId", WorkflowId);
            writer.WriteCollectionOfObjectValues<global::Soenneker.N8n.OpenApiClient.Models.GetWorkflow200ResponseActiveVersionWorkflowPublishHistoryItem>("workflowPublishHistory", WorkflowPublishHistory);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
