// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.N8n.OpenApiClient.Models
{
    /// <summary>
    /// Composed type wrapper for classes <see cref="bool"/>, <see cref="global::Soenneker.N8n.OpenApiClient.Models.GetWorkflows200ResponseDataItemSettingsSaveManualExecutionsOneOf2"/>
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class GetWorkflows200ResponseDataItemSettingsSaveManualExecutions : IComposedTypeWrapper, IParsable
    {
        /// <summary>Composed type representation for type <see cref="bool"/></summary>
        public bool? Boolean { get; set; }
        /// <summary>Composed type representation for type <see cref="global::Soenneker.N8n.OpenApiClient.Models.GetWorkflows200ResponseDataItemSettingsSaveManualExecutionsOneOf2"/></summary>
        public global::Soenneker.N8n.OpenApiClient.Models.GetWorkflows200ResponseDataItemSettingsSaveManualExecutionsOneOf2? GetWorkflows200ResponseDataItemSettingsSaveManualExecutionsOneOf2 { get; set; }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.N8n.OpenApiClient.Models.GetWorkflows200ResponseDataItemSettingsSaveManualExecutions"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.N8n.OpenApiClient.Models.GetWorkflows200ResponseDataItemSettingsSaveManualExecutions CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            var mappingValue = parseNode.GetChildNode("")?.GetStringValue();
            var result = new global::Soenneker.N8n.OpenApiClient.Models.GetWorkflows200ResponseDataItemSettingsSaveManualExecutions();
            if(parseNode.GetEnumValue<global::Soenneker.N8n.OpenApiClient.Models.GetWorkflows200ResponseDataItemSettingsSaveManualExecutionsOneOf2>() is global::Soenneker.N8n.OpenApiClient.Models.GetWorkflows200ResponseDataItemSettingsSaveManualExecutionsOneOf2 getWorkflows200ResponseDataItemSettingsSaveManualExecutionsOneOf2Value)
            {
                result.GetWorkflows200ResponseDataItemSettingsSaveManualExecutionsOneOf2 = getWorkflows200ResponseDataItemSettingsSaveManualExecutionsOneOf2Value;
            }
            else if(parseNode.GetBoolValue() is bool booleanValue)
            {
                result.Boolean = booleanValue;
            }
            return result;
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>();
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            if(GetWorkflows200ResponseDataItemSettingsSaveManualExecutionsOneOf2 != null)
            {
                writer.WriteEnumValue<global::Soenneker.N8n.OpenApiClient.Models.GetWorkflows200ResponseDataItemSettingsSaveManualExecutionsOneOf2>(null, GetWorkflows200ResponseDataItemSettingsSaveManualExecutionsOneOf2);
            }
            else if(Boolean != null)
            {
                writer.WriteBoolValue(null, Boolean);
            }
        }
    }
}
#pragma warning restore CS0618
