// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.N8n.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum GitConnectionPublicDtoGeneratedKeyGeneratorType
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "ed25519")]
        #pragma warning disable CS1591
        Ed25519,
        #pragma warning restore CS1591
        [EnumMember(Value = "rsa")]
        #pragma warning disable CS1591
        Rsa,
        #pragma warning restore CS1591
    }
}
