// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.N8n.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum ImportBlockingIssueOneOf5Kind
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "parent-mismatch")]
        #pragma warning disable CS1591
        ParentMismatch,
        #pragma warning restore CS1591
        [EnumMember(Value = "id-in-other-project")]
        #pragma warning disable CS1591
        IdInOtherProject,
        #pragma warning restore CS1591
        [EnumMember(Value = "fail-policy")]
        #pragma warning disable CS1591
        FailPolicy,
        #pragma warning restore CS1591
    }
}
