// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.N8n.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum ImportBlockingIssueOneOf11Type
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "variable-limit-exceeded")]
        #pragma warning disable CS1591
        VariableLimitExceeded,
        #pragma warning restore CS1591
    }
}
