// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.N8n.OpenApiClient.Models
{
    /// <summary>
    /// Composed type wrapper for classes <see cref="global::Soenneker.N8n.OpenApiClient.Models.InsertDataTableRows200Member1"/>, <see cref="global::Soenneker.N8n.OpenApiClient.Models.InsertDataTableRows200_Branch2"/>, <see cref="global::Soenneker.N8n.OpenApiClient.Models.InsertDataTableRows200_Branch3"/>
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class InsertDataTableRows200 : IComposedTypeWrapper, IParsable
    {
        /// <summary>Composed type representation for type <see cref="global::Soenneker.N8n.OpenApiClient.Models.InsertDataTableRows200_Branch2"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.N8n.OpenApiClient.Models.InsertDataTableRows200_Branch2? InsertDataTableRows200Branch2 { get; set; }
#nullable restore
#else
        public global::Soenneker.N8n.OpenApiClient.Models.InsertDataTableRows200_Branch2 InsertDataTableRows200Branch2 { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.N8n.OpenApiClient.Models.InsertDataTableRows200_Branch3"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.N8n.OpenApiClient.Models.InsertDataTableRows200_Branch3? InsertDataTableRows200Branch3 { get; set; }
#nullable restore
#else
        public global::Soenneker.N8n.OpenApiClient.Models.InsertDataTableRows200_Branch3 InsertDataTableRows200Branch3 { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.N8n.OpenApiClient.Models.InsertDataTableRows200Member1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.N8n.OpenApiClient.Models.InsertDataTableRows200Member1? InsertDataTableRows200Member1 { get; set; }
#nullable restore
#else
        public global::Soenneker.N8n.OpenApiClient.Models.InsertDataTableRows200Member1 InsertDataTableRows200Member1 { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.N8n.OpenApiClient.Models.InsertDataTableRows200"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.N8n.OpenApiClient.Models.InsertDataTableRows200 CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            var mappingValue = parseNode.GetChildNode("type")?.GetStringValue();
            var result = new global::Soenneker.N8n.OpenApiClient.Models.InsertDataTableRows200();
            if("InsertDataTableRows200_2".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.InsertDataTableRows200Branch2 = new global::Soenneker.N8n.OpenApiClient.Models.InsertDataTableRows200_Branch2();
            }
            else if("InsertDataTableRows200_3".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.InsertDataTableRows200Branch3 = new global::Soenneker.N8n.OpenApiClient.Models.InsertDataTableRows200_Branch3();
            }
            else if("".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.InsertDataTableRows200Member1 = new global::Soenneker.N8n.OpenApiClient.Models.InsertDataTableRows200Member1();
            }
            return result;
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            if(InsertDataTableRows200Branch2 != null)
            {
                return InsertDataTableRows200Branch2.GetFieldDeserializers();
            }
            else if(InsertDataTableRows200Branch3 != null)
            {
                return InsertDataTableRows200Branch3.GetFieldDeserializers();
            }
            else if(InsertDataTableRows200Member1 != null)
            {
                return InsertDataTableRows200Member1.GetFieldDeserializers();
            }
            return new Dictionary<string, Action<IParseNode>>();
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            if(InsertDataTableRows200Branch2 != null)
            {
                writer.WriteObjectValue<global::Soenneker.N8n.OpenApiClient.Models.InsertDataTableRows200_Branch2>(null, InsertDataTableRows200Branch2);
            }
            else if(InsertDataTableRows200Branch3 != null)
            {
                writer.WriteObjectValue<global::Soenneker.N8n.OpenApiClient.Models.InsertDataTableRows200_Branch3>(null, InsertDataTableRows200Branch3);
            }
            else if(InsertDataTableRows200Member1 != null)
            {
                writer.WriteObjectValue<global::Soenneker.N8n.OpenApiClient.Models.InsertDataTableRows200Member1>(null, InsertDataTableRows200Member1);
            }
        }
    }
}
#pragma warning restore CS0618
