// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.N8n.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum Insights_failureRate_unit
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "ratio")]
        #pragma warning disable CS1591
        Ratio,
        #pragma warning restore CS1591
    }
}
