// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.N8n.OpenApiClient.Models
{
    /// <summary>Whether the sync was a dry run or applied live.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum LdapSyncHistoryRunMode
    {
        [EnumMember(Value = "dry")]
        #pragma warning disable CS1591
        Dry,
        #pragma warning restore CS1591
        [EnumMember(Value = "live")]
        #pragma warning disable CS1591
        Live,
        #pragma warning restore CS1591
    }
}
