// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.N8n.OpenApiClient.Models
{
    /// <summary>
    /// Full LDAP configuration. Use empty strings for unset fields.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class LdapConfigurationUpdate : IParsable
    {
        /// <summary>Whether to allow unauthorized (self-signed) certificates.</summary>
        public bool? AllowUnauthorizedCerts { get; set; }
        /// <summary>Base DN for LDAP search queries.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? BaseDn { get; set; }
#nullable restore
#else
        public string BaseDn { get; set; }
#endif
        /// <summary>DN of the LDAP admin user for binding.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? BindingAdminDn { get; set; }
#nullable restore
#else
        public string BindingAdminDn { get; set; }
#endif
        /// <summary>Password for the LDAP admin user. To keep an existing password unchanged, submit the blanking placeholder from a prior GET response. Use an empty string to clear the password.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? BindingAdminPassword { get; set; }
#nullable restore
#else
        public string BindingAdminPassword { get; set; }
#endif
        /// <summary>LDAP server port.</summary>
        public int? ConnectionPort { get; set; }
        /// <summary>TLS/SSL security mode for the LDAP connection.</summary>
        public global::Soenneker.N8n.OpenApiClient.Models.LdapConfigurationUpdateConnectionSecurity? ConnectionSecurity { get; set; }
        /// <summary>LDAP server URL.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ConnectionUrl { get; set; }
#nullable restore
#else
        public string ConnectionUrl { get; set; }
#endif
        /// <summary>LDAP attribute mapped to the user&apos;s email.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? EmailAttribute { get; set; }
#nullable restore
#else
        public string EmailAttribute { get; set; }
#endif
        /// <summary>Whether to enforce that email addresses are unique across LDAP users. When true, if two users have the same email, only the first will be imported.</summary>
        public bool? EnforceEmailUniqueness { get; set; }
        /// <summary>LDAP attribute mapped to the user&apos;s first name.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? FirstNameAttribute { get; set; }
#nullable restore
#else
        public string FirstNameAttribute { get; set; }
#endif
        /// <summary>LDAP attribute mapped to the user&apos;s last name.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? LastNameAttribute { get; set; }
#nullable restore
#else
        public string LastNameAttribute { get; set; }
#endif
        /// <summary>LDAP attribute that uniquely identifies a user.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? LdapIdAttribute { get; set; }
#nullable restore
#else
        public string LdapIdAttribute { get; set; }
#endif
        /// <summary>Whether LDAP login is enabled. Setting this to false is destructive — it deletes all stored LDAP user identities and disables synchronization.</summary>
        public bool? LoginEnabled { get; set; }
        /// <summary>LDAP attribute used for login (usually the same as emailAttribute).</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? LoginIdAttribute { get; set; }
#nullable restore
#else
        public string LoginIdAttribute { get; set; }
#endif
        /// <summary>Label shown on the LDAP login button.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? LoginLabel { get; set; }
#nullable restore
#else
        public string LoginLabel { get; set; }
#endif
        /// <summary>Number of LDAP entries to fetch per search page.</summary>
        public int? SearchPageSize { get; set; }
        /// <summary>LDAP search timeout in seconds.</summary>
        public int? SearchTimeout { get; set; }
        /// <summary>Whether automatic LDAP synchronization is enabled.</summary>
        public bool? SynchronizationEnabled { get; set; }
        /// <summary>Interval in minutes between automatic synchronizations. Ignored if synchronizationEnabled is false.</summary>
        public int? SynchronizationInterval { get; set; }
        /// <summary>Additional LDAP filter to apply when searching for users. Use an empty string for no additional filter.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? UserFilter { get; set; }
#nullable restore
#else
        public string UserFilter { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.N8n.OpenApiClient.Models.LdapConfigurationUpdate"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.N8n.OpenApiClient.Models.LdapConfigurationUpdate CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.N8n.OpenApiClient.Models.LdapConfigurationUpdate();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "allowUnauthorizedCerts", n => { AllowUnauthorizedCerts = n.GetBoolValue(); } },
                { "baseDn", n => { BaseDn = n.GetStringValue(); } },
                { "bindingAdminDn", n => { BindingAdminDn = n.GetStringValue(); } },
                { "bindingAdminPassword", n => { BindingAdminPassword = n.GetStringValue(); } },
                { "connectionPort", n => { ConnectionPort = n.GetIntValue(); } },
                { "connectionSecurity", n => { ConnectionSecurity = n.GetEnumValue<global::Soenneker.N8n.OpenApiClient.Models.LdapConfigurationUpdateConnectionSecurity>(); } },
                { "connectionUrl", n => { ConnectionUrl = n.GetStringValue(); } },
                { "emailAttribute", n => { EmailAttribute = n.GetStringValue(); } },
                { "enforceEmailUniqueness", n => { EnforceEmailUniqueness = n.GetBoolValue(); } },
                { "firstNameAttribute", n => { FirstNameAttribute = n.GetStringValue(); } },
                { "lastNameAttribute", n => { LastNameAttribute = n.GetStringValue(); } },
                { "ldapIdAttribute", n => { LdapIdAttribute = n.GetStringValue(); } },
                { "loginEnabled", n => { LoginEnabled = n.GetBoolValue(); } },
                { "loginIdAttribute", n => { LoginIdAttribute = n.GetStringValue(); } },
                { "loginLabel", n => { LoginLabel = n.GetStringValue(); } },
                { "searchPageSize", n => { SearchPageSize = n.GetIntValue(); } },
                { "searchTimeout", n => { SearchTimeout = n.GetIntValue(); } },
                { "synchronizationEnabled", n => { SynchronizationEnabled = n.GetBoolValue(); } },
                { "synchronizationInterval", n => { SynchronizationInterval = n.GetIntValue(); } },
                { "userFilter", n => { UserFilter = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteBoolValue("allowUnauthorizedCerts", AllowUnauthorizedCerts);
            writer.WriteStringValue("baseDn", BaseDn);
            writer.WriteStringValue("bindingAdminDn", BindingAdminDn);
            writer.WriteStringValue("bindingAdminPassword", BindingAdminPassword);
            writer.WriteIntValue("connectionPort", ConnectionPort);
            writer.WriteEnumValue<global::Soenneker.N8n.OpenApiClient.Models.LdapConfigurationUpdateConnectionSecurity>("connectionSecurity", ConnectionSecurity);
            writer.WriteStringValue("connectionUrl", ConnectionUrl);
            writer.WriteStringValue("emailAttribute", EmailAttribute);
            writer.WriteBoolValue("enforceEmailUniqueness", EnforceEmailUniqueness);
            writer.WriteStringValue("firstNameAttribute", FirstNameAttribute);
            writer.WriteStringValue("lastNameAttribute", LastNameAttribute);
            writer.WriteStringValue("ldapIdAttribute", LdapIdAttribute);
            writer.WriteBoolValue("loginEnabled", LoginEnabled);
            writer.WriteStringValue("loginIdAttribute", LoginIdAttribute);
            writer.WriteStringValue("loginLabel", LoginLabel);
            writer.WriteIntValue("searchPageSize", SearchPageSize);
            writer.WriteIntValue("searchTimeout", SearchTimeout);
            writer.WriteBoolValue("synchronizationEnabled", SynchronizationEnabled);
            writer.WriteIntValue("synchronizationInterval", SynchronizationInterval);
            writer.WriteStringValue("userFilter", UserFilter);
        }
    }
}
#pragma warning restore CS0618
