// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.N8n.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class ListFolders200ResponseDataItem : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The createdAt property</summary>
        public DateTimeOffset? CreatedAt { get; private set; }
        /// <summary>The homeProject property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.N8n.OpenApiClient.Models.ListFolders200ResponseDataItemHomeProject? HomeProject { get; set; }
#nullable restore
#else
        public global::Soenneker.N8n.OpenApiClient.Models.ListFolders200ResponseDataItemHomeProject HomeProject { get; set; }
#endif
        /// <summary>The id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Id { get; private set; }
#nullable restore
#else
        public string Id { get; private set; }
#endif
        /// <summary>The name property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>The parentFolder property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.N8n.OpenApiClient.Models.ListFolders200ResponseDataItemParentFolder? ParentFolder { get; set; }
#nullable restore
#else
        public global::Soenneker.N8n.OpenApiClient.Models.ListFolders200ResponseDataItemParentFolder ParentFolder { get; set; }
#endif
        /// <summary>The parentFolderId property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ParentFolderId { get; set; }
#nullable restore
#else
        public string ParentFolderId { get; set; }
#endif
        /// <summary>Names of every folder from the project root down to this folder.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? Path { get; private set; }
#nullable restore
#else
        public List<string> Path { get; private set; }
#endif
        /// <summary>Number of folders the folder holds.</summary>
        public double? SubFolderCount { get; private set; }
        /// <summary>The tags property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.N8n.OpenApiClient.Models.ListFolders200ResponseDataItemTagsItem>? Tags { get; set; }
#nullable restore
#else
        public List<global::Soenneker.N8n.OpenApiClient.Models.ListFolders200ResponseDataItemTagsItem> Tags { get; set; }
#endif
        /// <summary>The updatedAt property</summary>
        public DateTimeOffset? UpdatedAt { get; private set; }
        /// <summary>Number of workflows the folder holds.</summary>
        public double? WorkflowCount { get; private set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.N8n.OpenApiClient.Models.ListFolders200ResponseDataItem"/> and sets the default values.
        /// </summary>
        public ListFolders200ResponseDataItem()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.N8n.OpenApiClient.Models.ListFolders200ResponseDataItem"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.N8n.OpenApiClient.Models.ListFolders200ResponseDataItem CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.N8n.OpenApiClient.Models.ListFolders200ResponseDataItem();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "createdAt", n => { CreatedAt = n.GetDateTimeOffsetValue(); } },
                { "homeProject", n => { HomeProject = n.GetObjectValue<global::Soenneker.N8n.OpenApiClient.Models.ListFolders200ResponseDataItemHomeProject>(global::Soenneker.N8n.OpenApiClient.Models.ListFolders200ResponseDataItemHomeProject.CreateFromDiscriminatorValue); } },
                { "id", n => { Id = n.GetStringValue(); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "parentFolder", n => { ParentFolder = n.GetObjectValue<global::Soenneker.N8n.OpenApiClient.Models.ListFolders200ResponseDataItemParentFolder>(global::Soenneker.N8n.OpenApiClient.Models.ListFolders200ResponseDataItemParentFolder.CreateFromDiscriminatorValue); } },
                { "parentFolderId", n => { ParentFolderId = n.GetStringValue(); } },
                { "path", n => { Path = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "subFolderCount", n => { SubFolderCount = n.GetDoubleValue(); } },
                { "tags", n => { Tags = n.GetCollectionOfObjectValues<global::Soenneker.N8n.OpenApiClient.Models.ListFolders200ResponseDataItemTagsItem>(global::Soenneker.N8n.OpenApiClient.Models.ListFolders200ResponseDataItemTagsItem.CreateFromDiscriminatorValue)?.AsList(); } },
                { "updatedAt", n => { UpdatedAt = n.GetDateTimeOffsetValue(); } },
                { "workflowCount", n => { WorkflowCount = n.GetDoubleValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Soenneker.N8n.OpenApiClient.Models.ListFolders200ResponseDataItemHomeProject>("homeProject", HomeProject);
            writer.WriteStringValue("name", Name);
            writer.WriteObjectValue<global::Soenneker.N8n.OpenApiClient.Models.ListFolders200ResponseDataItemParentFolder>("parentFolder", ParentFolder);
            writer.WriteStringValue("parentFolderId", ParentFolderId);
            writer.WriteCollectionOfObjectValues<global::Soenneker.N8n.OpenApiClient.Models.ListFolders200ResponseDataItemTagsItem>("tags", Tags);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
