// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.N8n.OpenApiClient.Models
{
    /// <summary>The prompt parameter to use when authenticating.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum OidcConfigurationUpdatePrompt
    {
        [EnumMember(Value = "none")]
        #pragma warning disable CS1591
        None,
        #pragma warning restore CS1591
        [EnumMember(Value = "login")]
        #pragma warning disable CS1591
        Login,
        #pragma warning restore CS1591
        [EnumMember(Value = "consent")]
        #pragma warning disable CS1591
        Consent,
        #pragma warning restore CS1591
        [EnumMember(Value = "select_account")]
        #pragma warning disable CS1591
        SelectAccount,
        #pragma warning restore CS1591
        [EnumMember(Value = "create")]
        #pragma warning disable CS1591
        Create,
        #pragma warning restore CS1591
    }
}
