// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.N8n.OpenApiClient.Models
{
    /// <summary>
    /// The OpenTelemetry configuration, matching the fields exposed in the UI. On a write this is a full replacement: every field must be provided. Fields managed declaratively via environment variables are returned with their effective value and ignored on write.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class OtelSettings : IParsable
    {
        /// <summary>Whether OpenTelemetry tracing is enabled.</summary>
        public bool? Enabled { get; set; }
        /// <summary>The base URL of the OTLP collector to export traces to.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ExporterEndpoint { get; set; }
#nullable restore
#else
        public string ExporterEndpoint { get; set; }
#endif
        /// <summary>Additional headers sent to the OTLP collector, as a single string of comma-separated `key=value` pairs (e.g. `authorization=Bearer my-token,x-tenant-id=acme`). Whitespace around each key and value is trimmed; a value may contain spaces but not commas. Use an empty string when unused.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ExporterHeaders { get; set; }
#nullable restore
#else
        public string ExporterHeaders { get; set; }
#endif
        /// <summary>The `service.name` resource attribute reported on every span.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ExporterServiceName { get; set; }
#nullable restore
#else
        public string ExporterServiceName { get; set; }
#endif
        /// <summary>The path appended to the endpoint for the OTLP traces signal.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ExporterTracingPath { get; set; }
#nullable restore
#else
        public string ExporterTracingPath { get; set; }
#endif
        /// <summary>Whether to emit a span for each node execution in addition to the workflow span.</summary>
        public bool? IncludeNodeSpans { get; set; }
        /// <summary>Whether to inject trace context headers into outbound HTTP requests made by nodes.</summary>
        public bool? InjectOutbound { get; set; }
        /// <summary>When true, only production executions of published (active) workflows are traced, not manual/test runs.</summary>
        public bool? ProductionExecutionsOnly { get; set; }
        /// <summary>How long, in milliseconds, to wait when checking the collector is reachable. Also used as the timeout for the test-trace endpoint.</summary>
        public int? StartupConnectivityTimeoutMs { get; set; }
        /// <summary>The ratio of traces to sample, between 0 (none) and 1 (all).</summary>
        public double? TracesSampleRate { get; set; }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.N8n.OpenApiClient.Models.OtelSettings"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.N8n.OpenApiClient.Models.OtelSettings CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.N8n.OpenApiClient.Models.OtelSettings();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "enabled", n => { Enabled = n.GetBoolValue(); } },
                { "exporterEndpoint", n => { ExporterEndpoint = n.GetStringValue(); } },
                { "exporterHeaders", n => { ExporterHeaders = n.GetStringValue(); } },
                { "exporterServiceName", n => { ExporterServiceName = n.GetStringValue(); } },
                { "exporterTracingPath", n => { ExporterTracingPath = n.GetStringValue(); } },
                { "includeNodeSpans", n => { IncludeNodeSpans = n.GetBoolValue(); } },
                { "injectOutbound", n => { InjectOutbound = n.GetBoolValue(); } },
                { "productionExecutionsOnly", n => { ProductionExecutionsOnly = n.GetBoolValue(); } },
                { "startupConnectivityTimeoutMs", n => { StartupConnectivityTimeoutMs = n.GetIntValue(); } },
                { "tracesSampleRate", n => { TracesSampleRate = n.GetDoubleValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteBoolValue("enabled", Enabled);
            writer.WriteStringValue("exporterEndpoint", ExporterEndpoint);
            writer.WriteStringValue("exporterHeaders", ExporterHeaders);
            writer.WriteStringValue("exporterServiceName", ExporterServiceName);
            writer.WriteStringValue("exporterTracingPath", ExporterTracingPath);
            writer.WriteBoolValue("includeNodeSpans", IncludeNodeSpans);
            writer.WriteBoolValue("injectOutbound", InjectOutbound);
            writer.WriteBoolValue("productionExecutionsOnly", ProductionExecutionsOnly);
            writer.WriteIntValue("startupConnectivityTimeoutMs", StartupConnectivityTimeoutMs);
            writer.WriteDoubleValue("tracesSampleRate", TracesSampleRate);
        }
    }
}
#pragma warning restore CS0618
