// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.N8n.OpenApiClient.Models
{
    /// <summary>The wire protocol used to export spans. Collectors conventionally serve OTLP/HTTP on port 4318 and OTLP/gRPC on port 4317. The endpoint scheme (`http://` or `https://`) controls TLS for both protocols. Optional: a write that omits it selects `http/protobuf`, but an instance that sets this field to another value with an environment variable rejects that write with 409.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum OtelSettingsExporterProtocol
    {
        [EnumMember(Value = "http/protobuf")]
        #pragma warning disable CS1591
        HttpProtobuf,
        #pragma warning restore CS1591
        [EnumMember(Value = "grpc")]
        #pragma warning disable CS1591
        Grpc,
        #pragma warning restore CS1591
    }
}
