// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.N8n.OpenApiClient.Models
{
    /// <summary>What happens when a selected workflow matches an existing workflow by source id in the target project. `new-version` (default) updates it and creates a new version; `fail` rejects the import when any matching workflow exists; `skip` leaves matching workflows unchanged. An archive state change also needs the `workflow:delete` scope.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum PostN8NPackagesImportSelectionFormDataRequestWorkflowConflictPolicy
    {
        [EnumMember(Value = "new-version")]
        #pragma warning disable CS1591
        NewVersion,
        #pragma warning restore CS1591
        [EnumMember(Value = "fail")]
        #pragma warning disable CS1591
        Fail,
        #pragma warning restore CS1591
        [EnumMember(Value = "skip")]
        #pragma warning disable CS1591
        Skip,
        #pragma warning restore CS1591
    }
}
