// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.N8n.OpenApiClient.Models
{
    /// <summary>What to do when a workflow in the package uses a node type — or a version of a node type — this instance does not have. `fail` (default) rejects the import before anything is written, listing every missing `(nodeType, typeVersion)` pair and the workflows that use it. `import-anyway` imports the package; workflows containing missing node types are never published by this import, regardless of `workflowPublishingPolicy`.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum PostN8NPackagesImportFormDataRequestMissingNodeTypeMode
    {
        [EnumMember(Value = "fail")]
        #pragma warning disable CS1591
        Fail,
        #pragma warning restore CS1591
        [EnumMember(Value = "import-anyway")]
        #pragma warning disable CS1591
        ImportAnyway,
        #pragma warning restore CS1591
    }
}
