// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.N8n.OpenApiClient.Models
{
    /// <summary>What to do when a tag referenced by the package&apos;s workflows has no tag with the same id on the target instance (tags are matched by source id, never by name). `create` (default) creates the tag globally with its package (source) id and name; when the import would create a tag this needs an API key carrying the `tag:create` scope. `do-nothing` imports the workflows without the missing tags — nothing is created and the dropped names are listed under `tags.skipped`.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum PostN8NPackagesImportFormDataRequestTagMissingMode
    {
        [EnumMember(Value = "create")]
        #pragma warning disable CS1591
        Create,
        #pragma warning restore CS1591
        [EnumMember(Value = "do-nothing")]
        #pragma warning disable CS1591
        DoNothing,
        #pragma warning restore CS1591
    }
}
