// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.N8n.OpenApiClient.Models
{
    /// <summary>Present when `state` is `blocked`: the imported version could not be published and no version is active.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum PostN8NPackagesImport200ResponseWorkflowsItemPublishingBlockedReason
    {
        [EnumMember(Value = "stub-credential")]
        #pragma warning disable CS1591
        StubCredential,
        #pragma warning restore CS1591
        [EnumMember(Value = "missing-node-type")]
        #pragma warning disable CS1591
        MissingNodeType,
        #pragma warning restore CS1591
    }
}
