// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.N8n.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum PromotionProviderPublicDtoGeneratedAuthType
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "ssh-key")]
        #pragma warning disable CS1591
        SshKey,
        #pragma warning restore CS1591
        [EnumMember(Value = "token")]
        #pragma warning disable CS1591
        Token,
        #pragma warning restore CS1591
    }
}
