// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.N8n.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum PromotionCheckoutPublicDtoGeneratedDirection
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "apply")]
        #pragma warning disable CS1591
        Apply,
        #pragma warning restore CS1591
        [EnumMember(Value = "promote")]
        #pragma warning disable CS1591
        Promote,
        #pragma warning restore CS1591
    }
}
