// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.N8n.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum PushSourceControl200ResponseDataItemPublishingErrorDetailsReason
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "review_pending")]
        #pragma warning disable CS1591
        ReviewPending,
        #pragma warning restore CS1591
        [EnumMember(Value = "changes_requested")]
        #pragma warning disable CS1591
        ChangesRequested,
        #pragma warning restore CS1591
        [EnumMember(Value = "insufficient_api_key_scope")]
        #pragma warning disable CS1591
        InsufficientApiKeyScope,
        #pragma warning restore CS1591
        [EnumMember(Value = "insufficient_permissions")]
        #pragma warning disable CS1591
        InsufficientPermissions,
        #pragma warning restore CS1591
    }
}
