// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.N8n.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class RetryExecution200Response : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Annotation on the original execution. Absent when it carries none.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.N8n.OpenApiClient.Models.RetryExecution200ResponseAnnotation? Annotation { get; set; }
#nullable restore
#else
        public global::Soenneker.N8n.OpenApiClient.Models.RetryExecution200ResponseAnnotation Annotation { get; set; }
#endif
        /// <summary>Execution metadata carried over from the original execution.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.N8n.OpenApiClient.Models.RetryExecution200ResponseCustomData? CustomData { get; set; }
#nullable restore
#else
        public global::Soenneker.N8n.OpenApiClient.Models.RetryExecution200ResponseCustomData CustomData { get; set; }
#endif
        /// <summary>Run data of the new execution.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.N8n.OpenApiClient.Models.RetryExecution200ResponseData? Data { get; set; }
#nullable restore
#else
        public global::Soenneker.N8n.OpenApiClient.Models.RetryExecution200ResponseData Data { get; set; }
#endif
        /// <summary>Whether the execution ran to completion. Use `status` instead.</summary>
        [Obsolete("")]
        public bool? Finished { get; set; }
        /// <summary>ID of the new execution that the retry started.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Id { get; set; }
#nullable restore
#else
        public string Id { get; set; }
#endif
        /// <summary>The mode property</summary>
        public global::Soenneker.N8n.OpenApiClient.Models.RetryExecution200ResponseMode? Mode { get; set; }
        /// <summary>ID of the execution this one is a retry of.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? RetryOf { get; set; }
#nullable restore
#else
        public string RetryOf { get; set; }
#endif
        /// <summary>The time at which the new execution started.</summary>
        public DateTimeOffset? StartedAt { get; set; }
        /// <summary>The status property</summary>
        public global::Soenneker.N8n.OpenApiClient.Models.RetryExecution200ResponseStatus? Status { get; set; }
        /// <summary>Where the execution data is stored.</summary>
        public global::Soenneker.N8n.OpenApiClient.Models.RetryExecution200ResponseStoredAt? StoredAt { get; set; }
        /// <summary>The time at which a waiting execution resumes.</summary>
        public DateTimeOffset? WaitTill { get; set; }
        /// <summary>The workflow as it was saved when the original execution ran. `loadWorkflow` changes which workflow the retry runs, not what this field reports.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.N8n.OpenApiClient.Models.RetryExecution200ResponseWorkflowData? WorkflowData { get; set; }
#nullable restore
#else
        public global::Soenneker.N8n.OpenApiClient.Models.RetryExecution200ResponseWorkflowData WorkflowData { get; set; }
#endif
        /// <summary>The workflowId property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? WorkflowId { get; set; }
#nullable restore
#else
        public string WorkflowId { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.N8n.OpenApiClient.Models.RetryExecution200Response"/> and sets the default values.
        /// </summary>
        public RetryExecution200Response()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.N8n.OpenApiClient.Models.RetryExecution200Response"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.N8n.OpenApiClient.Models.RetryExecution200Response CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.N8n.OpenApiClient.Models.RetryExecution200Response();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "annotation", n => { Annotation = n.GetObjectValue<global::Soenneker.N8n.OpenApiClient.Models.RetryExecution200ResponseAnnotation>(global::Soenneker.N8n.OpenApiClient.Models.RetryExecution200ResponseAnnotation.CreateFromDiscriminatorValue); } },
                { "customData", n => { CustomData = n.GetObjectValue<global::Soenneker.N8n.OpenApiClient.Models.RetryExecution200ResponseCustomData>(global::Soenneker.N8n.OpenApiClient.Models.RetryExecution200ResponseCustomData.CreateFromDiscriminatorValue); } },
                { "data", n => { Data = n.GetObjectValue<global::Soenneker.N8n.OpenApiClient.Models.RetryExecution200ResponseData>(global::Soenneker.N8n.OpenApiClient.Models.RetryExecution200ResponseData.CreateFromDiscriminatorValue); } },
                { "finished", n => { Finished = n.GetBoolValue(); } },
                { "id", n => { Id = n.GetStringValue(); } },
                { "mode", n => { Mode = n.GetEnumValue<global::Soenneker.N8n.OpenApiClient.Models.RetryExecution200ResponseMode>(); } },
                { "retryOf", n => { RetryOf = n.GetStringValue(); } },
                { "startedAt", n => { StartedAt = n.GetDateTimeOffsetValue(); } },
                { "status", n => { Status = n.GetEnumValue<global::Soenneker.N8n.OpenApiClient.Models.RetryExecution200ResponseStatus>(); } },
                { "storedAt", n => { StoredAt = n.GetEnumValue<global::Soenneker.N8n.OpenApiClient.Models.RetryExecution200ResponseStoredAt>(); } },
                { "waitTill", n => { WaitTill = n.GetDateTimeOffsetValue(); } },
                { "workflowData", n => { WorkflowData = n.GetObjectValue<global::Soenneker.N8n.OpenApiClient.Models.RetryExecution200ResponseWorkflowData>(global::Soenneker.N8n.OpenApiClient.Models.RetryExecution200ResponseWorkflowData.CreateFromDiscriminatorValue); } },
                { "workflowId", n => { WorkflowId = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Soenneker.N8n.OpenApiClient.Models.RetryExecution200ResponseAnnotation>("annotation", Annotation);
            writer.WriteObjectValue<global::Soenneker.N8n.OpenApiClient.Models.RetryExecution200ResponseCustomData>("customData", CustomData);
            writer.WriteObjectValue<global::Soenneker.N8n.OpenApiClient.Models.RetryExecution200ResponseData>("data", Data);
            writer.WriteBoolValue("finished", Finished);
            writer.WriteStringValue("id", Id);
            writer.WriteEnumValue<global::Soenneker.N8n.OpenApiClient.Models.RetryExecution200ResponseMode>("mode", Mode);
            writer.WriteStringValue("retryOf", RetryOf);
            writer.WriteDateTimeOffsetValue("startedAt", StartedAt);
            writer.WriteEnumValue<global::Soenneker.N8n.OpenApiClient.Models.RetryExecution200ResponseStatus>("status", Status);
            writer.WriteEnumValue<global::Soenneker.N8n.OpenApiClient.Models.RetryExecution200ResponseStoredAt>("storedAt", StoredAt);
            writer.WriteDateTimeOffsetValue("waitTill", WaitTill);
            writer.WriteObjectValue<global::Soenneker.N8n.OpenApiClient.Models.RetryExecution200ResponseWorkflowData>("workflowData", WorkflowData);
            writer.WriteStringValue("workflowId", WorkflowId);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
