// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.N8n.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class SamlConfigurationPublicDtoGenerated : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Assertion Consumer Service binding.</summary>
        public global::Soenneker.N8n.OpenApiClient.Models.SamlConfigurationPublicDtoGeneratedAcsBinding? AcsBinding { get; set; }
        /// <summary>Whether authentication requests are signed.</summary>
        public bool? AuthnRequestsSigned { get; set; }
        /// <summary>Whether the identity provider must assert that the user&apos;s email address is verified before a login is linked to an existing user by email. When disabled, only an explicit negative assertion is rejected.</summary>
        public bool? EmailVerifiedRequired { get; set; }
        /// <summary>Service provider entity ID (metadata URL).</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? EntityID { get; private set; }
#nullable restore
#else
        public string EntityID { get; private set; }
#endif
        /// <summary>Whether to ignore SSL certificate errors when fetching metadata from a URL.</summary>
        public bool? IgnoreSSL { get; set; }
        /// <summary>SAML login request binding.</summary>
        public global::Soenneker.N8n.OpenApiClient.Models.SamlConfigurationPublicDtoGeneratedLoginBinding? LoginBinding { get; set; }
        /// <summary>Whether SAML login is enabled.</summary>
        public bool? LoginEnabled { get; set; }
        /// <summary>Label shown on the SAML login button.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? LoginLabel { get; set; }
#nullable restore
#else
        public string LoginLabel { get; set; }
#endif
        /// <summary>Mapping of SAML attributes to n8n user fields.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.N8n.OpenApiClient.Models.SamlConfigurationPublicDtoGeneratedMapping? Mapping { get; set; }
#nullable restore
#else
        public global::Soenneker.N8n.OpenApiClient.Models.SamlConfigurationPublicDtoGeneratedMapping Mapping { get; set; }
#endif
        /// <summary>Identity provider metadata in XML format. Redacted on read when set because it contains IdP certificates; never echoed back in plaintext. Use an empty string when unset.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Metadata { get; set; }
#nullable restore
#else
        public string Metadata { get; set; }
#endif
        /// <summary>URL to fetch identity provider metadata from. Use an empty string when unset.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? MetadataUrl { get; set; }
#nullable restore
#else
        public string MetadataUrl { get; set; }
#endif
        /// <summary>Default relay state value for SAML requests. Use an empty string when unset.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? RelayState { get; set; }
#nullable restore
#else
        public string RelayState { get; set; }
#endif
        /// <summary>Assertion Consumer Service (ACS) return URL.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ReturnUrl { get; private set; }
#nullable restore
#else
        public string ReturnUrl { get; private set; }
#endif
        /// <summary>Configuration for the signature in SAML requests and responses.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.N8n.OpenApiClient.Models.SamlConfigurationPublicDtoGeneratedSignatureConfig? SignatureConfig { get; set; }
#nullable restore
#else
        public global::Soenneker.N8n.OpenApiClient.Models.SamlConfigurationPublicDtoGeneratedSignatureConfig SignatureConfig { get; set; }
#endif
        /// <summary>PEM-encoded certificate containing the public key matching the signing private key. Redacted on read when set; never echoed back in plaintext. Use an empty string when unset.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SigningCertificate { get; set; }
#nullable restore
#else
        public string SigningCertificate { get; set; }
#endif
        /// <summary>PEM-encoded private key for signing SAML AuthnRequests. Redacted on read when set; never echoed back in plaintext. Use an empty string when unset.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SigningPrivateKey { get; set; }
#nullable restore
#else
        public string SigningPrivateKey { get; set; }
#endif
        /// <summary>Whether signed assertions are required.</summary>
        public bool? WantAssertionsSigned { get; set; }
        /// <summary>Whether signed SAML messages are required.</summary>
        public bool? WantMessageSigned { get; set; }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.N8n.OpenApiClient.Models.SamlConfigurationPublicDtoGenerated"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.N8n.OpenApiClient.Models.SamlConfigurationPublicDtoGenerated CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.N8n.OpenApiClient.Models.SamlConfigurationPublicDtoGenerated();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "acsBinding", n => { AcsBinding = n.GetEnumValue<global::Soenneker.N8n.OpenApiClient.Models.SamlConfigurationPublicDtoGeneratedAcsBinding>(); } },
                { "authnRequestsSigned", n => { AuthnRequestsSigned = n.GetBoolValue(); } },
                { "emailVerifiedRequired", n => { EmailVerifiedRequired = n.GetBoolValue(); } },
                { "entityID", n => { EntityID = n.GetStringValue(); } },
                { "ignoreSSL", n => { IgnoreSSL = n.GetBoolValue(); } },
                { "loginBinding", n => { LoginBinding = n.GetEnumValue<global::Soenneker.N8n.OpenApiClient.Models.SamlConfigurationPublicDtoGeneratedLoginBinding>(); } },
                { "loginEnabled", n => { LoginEnabled = n.GetBoolValue(); } },
                { "loginLabel", n => { LoginLabel = n.GetStringValue(); } },
                { "mapping", n => { Mapping = n.GetObjectValue<global::Soenneker.N8n.OpenApiClient.Models.SamlConfigurationPublicDtoGeneratedMapping>(global::Soenneker.N8n.OpenApiClient.Models.SamlConfigurationPublicDtoGeneratedMapping.CreateFromDiscriminatorValue); } },
                { "metadata", n => { Metadata = n.GetStringValue(); } },
                { "metadataUrl", n => { MetadataUrl = n.GetStringValue(); } },
                { "relayState", n => { RelayState = n.GetStringValue(); } },
                { "returnUrl", n => { ReturnUrl = n.GetStringValue(); } },
                { "signatureConfig", n => { SignatureConfig = n.GetObjectValue<global::Soenneker.N8n.OpenApiClient.Models.SamlConfigurationPublicDtoGeneratedSignatureConfig>(global::Soenneker.N8n.OpenApiClient.Models.SamlConfigurationPublicDtoGeneratedSignatureConfig.CreateFromDiscriminatorValue); } },
                { "signingCertificate", n => { SigningCertificate = n.GetStringValue(); } },
                { "signingPrivateKey", n => { SigningPrivateKey = n.GetStringValue(); } },
                { "wantAssertionsSigned", n => { WantAssertionsSigned = n.GetBoolValue(); } },
                { "wantMessageSigned", n => { WantMessageSigned = n.GetBoolValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteEnumValue<global::Soenneker.N8n.OpenApiClient.Models.SamlConfigurationPublicDtoGeneratedAcsBinding>("acsBinding", AcsBinding);
            writer.WriteBoolValue("authnRequestsSigned", AuthnRequestsSigned);
            writer.WriteBoolValue("emailVerifiedRequired", EmailVerifiedRequired);
            writer.WriteBoolValue("ignoreSSL", IgnoreSSL);
            writer.WriteEnumValue<global::Soenneker.N8n.OpenApiClient.Models.SamlConfigurationPublicDtoGeneratedLoginBinding>("loginBinding", LoginBinding);
            writer.WriteBoolValue("loginEnabled", LoginEnabled);
            writer.WriteStringValue("loginLabel", LoginLabel);
            writer.WriteObjectValue<global::Soenneker.N8n.OpenApiClient.Models.SamlConfigurationPublicDtoGeneratedMapping>("mapping", Mapping);
            writer.WriteStringValue("metadata", Metadata);
            writer.WriteStringValue("metadataUrl", MetadataUrl);
            writer.WriteStringValue("relayState", RelayState);
            writer.WriteObjectValue<global::Soenneker.N8n.OpenApiClient.Models.SamlConfigurationPublicDtoGeneratedSignatureConfig>("signatureConfig", SignatureConfig);
            writer.WriteStringValue("signingCertificate", SigningCertificate);
            writer.WriteStringValue("signingPrivateKey", SigningPrivateKey);
            writer.WriteBoolValue("wantAssertionsSigned", WantAssertionsSigned);
            writer.WriteBoolValue("wantMessageSigned", WantMessageSigned);
        }
    }
}
#pragma warning restore CS0618
