// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.N8n.OpenApiClient.Models
{
    /// <summary>Minimum execution-data redaction level enforced across the instance.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum SecurityPolicyUpdateRedactionEnforcementFloor
    {
        [EnumMember(Value = "off")]
        #pragma warning disable CS1591
        Off,
        #pragma warning restore CS1591
        [EnumMember(Value = "production")]
        #pragma warning disable CS1591
        Production,
        #pragma warning restore CS1591
        [EnumMember(Value = "all")]
        #pragma warning disable CS1591
        All,
        #pragma warning restore CS1591
    }
}
