// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.N8n.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum TypeMismatchCode
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "type-mismatch")]
        #pragma warning disable CS1591
        TypeMismatch,
        #pragma warning restore CS1591
    }
}
