// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.N8n.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class UpdateWorkflowRequestActiveVersion : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Comma-separated list of author IDs who contributed to this version</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Authors { get; private set; }
#nullable restore
#else
        public string Authors { get; private set; }
#endif
        /// <summary>Whether this version was created by autosave</summary>
        public bool? Autosaved { get; private set; }
        /// <summary>Connections between nodes, keyed by source node name</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.N8n.OpenApiClient.Models.UpdateWorkflowRequestActiveVersionConnections? Connections { get; private set; }
#nullable restore
#else
        public global::Soenneker.N8n.OpenApiClient.Models.UpdateWorkflowRequestActiveVersionConnections Connections { get; private set; }
#endif
        /// <summary>The createdAt property</summary>
        public DateTimeOffset? CreatedAt { get; private set; }
        /// <summary>Optional description for this workflow version</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Description { get; private set; }
#nullable restore
#else
        public string Description { get; private set; }
#endif
        /// <summary>Optional name for this workflow version</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; private set; }
#nullable restore
#else
        public string Name { get; private set; }
#endif
        /// <summary>Visual groupings of nodes shown as frames on the canvas</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.N8n.OpenApiClient.Models.UpdateWorkflowRequestActiveVersionNodeGroupsItem>? NodeGroups { get; private set; }
#nullable restore
#else
        public List<global::Soenneker.N8n.OpenApiClient.Models.UpdateWorkflowRequestActiveVersionNodeGroupsItem> NodeGroups { get; private set; }
#endif
        /// <summary>Nodes that make up the workflow</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.N8n.OpenApiClient.Models.UpdateWorkflowRequestActiveVersionNodesItem>? Nodes { get; private set; }
#nullable restore
#else
        public List<global::Soenneker.N8n.OpenApiClient.Models.UpdateWorkflowRequestActiveVersionNodesItem> Nodes { get; private set; }
#endif
        /// <summary>The updatedAt property</summary>
        public DateTimeOffset? UpdatedAt { get; private set; }
        /// <summary>Unique identifier for this workflow version</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? VersionId { get; private set; }
#nullable restore
#else
        public string VersionId { get; private set; }
#endif
        /// <summary>The workflow this version belongs to</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? WorkflowId { get; private set; }
#nullable restore
#else
        public string WorkflowId { get; private set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.N8n.OpenApiClient.Models.UpdateWorkflowRequestActiveVersion"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.N8n.OpenApiClient.Models.UpdateWorkflowRequestActiveVersion CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.N8n.OpenApiClient.Models.UpdateWorkflowRequestActiveVersion();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "authors", n => { Authors = n.GetStringValue(); } },
                { "autosaved", n => { Autosaved = n.GetBoolValue(); } },
                { "connections", n => { Connections = n.GetObjectValue<global::Soenneker.N8n.OpenApiClient.Models.UpdateWorkflowRequestActiveVersionConnections>(global::Soenneker.N8n.OpenApiClient.Models.UpdateWorkflowRequestActiveVersionConnections.CreateFromDiscriminatorValue); } },
                { "createdAt", n => { CreatedAt = n.GetDateTimeOffsetValue(); } },
                { "description", n => { Description = n.GetStringValue(); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "nodeGroups", n => { NodeGroups = n.GetCollectionOfObjectValues<global::Soenneker.N8n.OpenApiClient.Models.UpdateWorkflowRequestActiveVersionNodeGroupsItem>(global::Soenneker.N8n.OpenApiClient.Models.UpdateWorkflowRequestActiveVersionNodeGroupsItem.CreateFromDiscriminatorValue)?.AsList(); } },
                { "nodes", n => { Nodes = n.GetCollectionOfObjectValues<global::Soenneker.N8n.OpenApiClient.Models.UpdateWorkflowRequestActiveVersionNodesItem>(global::Soenneker.N8n.OpenApiClient.Models.UpdateWorkflowRequestActiveVersionNodesItem.CreateFromDiscriminatorValue)?.AsList(); } },
                { "updatedAt", n => { UpdatedAt = n.GetDateTimeOffsetValue(); } },
                { "versionId", n => { VersionId = n.GetStringValue(); } },
                { "workflowId", n => { WorkflowId = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
        }
    }
}
#pragma warning restore CS0618
