// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.N8n.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum UpdateGitConnectionRequestConnectionType
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "ssh")]
        #pragma warning disable CS1591
        Ssh,
        #pragma warning restore CS1591
        [EnumMember(Value = "https")]
        #pragma warning disable CS1591
        Https,
        #pragma warning restore CS1591
    }
}
