// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.N8n.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class UpdateCredentialRequest : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The credential data. Required when changing credential type.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.N8n.OpenApiClient.Models.UpdateCredentialRequest_data? Data { get; set; }
#nullable restore
#else
        public global::Soenneker.N8n.OpenApiClient.Models.UpdateCredentialRequest_data Data { get; set; }
#endif
        /// <summary>Whether this credential is available globally</summary>
        public bool? IsGlobal { get; set; }
        /// <summary>If true, unredacts and merges existing credential data with the provided data. If false, replaces the entire data object.</summary>
        public bool? IsPartialData { get; set; }
        /// <summary>Whether this credential has resolvable fields</summary>
        public bool? IsResolvable { get; set; }
        /// <summary>The name of the credential</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>The credential type. If changing type, data must also be provided.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Type { get; set; }
#nullable restore
#else
        public string Type { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.N8n.OpenApiClient.Models.UpdateCredentialRequest"/> and sets the default values.
        /// </summary>
        public UpdateCredentialRequest()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.N8n.OpenApiClient.Models.UpdateCredentialRequest"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.N8n.OpenApiClient.Models.UpdateCredentialRequest CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.N8n.OpenApiClient.Models.UpdateCredentialRequest();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "data", n => { Data = n.GetObjectValue<global::Soenneker.N8n.OpenApiClient.Models.UpdateCredentialRequest_data>(global::Soenneker.N8n.OpenApiClient.Models.UpdateCredentialRequest_data.CreateFromDiscriminatorValue); } },
                { "isGlobal", n => { IsGlobal = n.GetBoolValue(); } },
                { "isPartialData", n => { IsPartialData = n.GetBoolValue(); } },
                { "isResolvable", n => { IsResolvable = n.GetBoolValue(); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "type", n => { Type = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Soenneker.N8n.OpenApiClient.Models.UpdateCredentialRequest_data>("data", Data);
            writer.WriteBoolValue("isGlobal", IsGlobal);
            writer.WriteBoolValue("isPartialData", IsPartialData);
            writer.WriteBoolValue("isResolvable", IsResolvable);
            writer.WriteStringValue("name", Name);
            writer.WriteStringValue("type", Type);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
