// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.N8n.OpenApiClient.Models
{
    /// <summary>
    /// Composed type wrapper for classes <see cref="global::Soenneker.N8n.OpenApiClient.Models.UpdateDataTableRowsRequestFilterFiltersItemConditionAnyOf1"/>, <see cref="global::Soenneker.N8n.OpenApiClient.Models.UpdateDataTableRowsRequestFilterFiltersItemConditionAnyOf2"/>, <see cref="global::Soenneker.N8n.OpenApiClient.Models.UpdateDataTableRowsRequestFilterFiltersItemConditionAnyOf3"/>, <see cref="global::Soenneker.N8n.OpenApiClient.Models.UpdateDataTableRowsRequestFilterFiltersItemConditionAnyOf4"/>, <see cref="global::Soenneker.N8n.OpenApiClient.Models.UpdateDataTableRowsRequestFilterFiltersItemConditionAnyOf5"/>, <see cref="global::Soenneker.N8n.OpenApiClient.Models.UpdateDataTableRowsRequestFilterFiltersItemConditionAnyOf6"/>, <see cref="global::Soenneker.N8n.OpenApiClient.Models.UpdateDataTableRowsRequestFilterFiltersItemConditionAnyOf7"/>, <see cref="global::Soenneker.N8n.OpenApiClient.Models.UpdateDataTableRowsRequestFilterFiltersItemConditionAnyOf8"/>
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class UpdateDataTableRowsRequestFilterFiltersItemCondition : IComposedTypeWrapper, IParsable
    {
        /// <summary>Composed type representation for type <see cref="global::Soenneker.N8n.OpenApiClient.Models.UpdateDataTableRowsRequestFilterFiltersItemConditionAnyOf1"/></summary>
        public global::Soenneker.N8n.OpenApiClient.Models.UpdateDataTableRowsRequestFilterFiltersItemConditionAnyOf1? UpdateDataTableRowsRequestFilterFiltersItemConditionAnyOf1 { get; set; }
        /// <summary>Composed type representation for type <see cref="global::Soenneker.N8n.OpenApiClient.Models.UpdateDataTableRowsRequestFilterFiltersItemConditionAnyOf2"/></summary>
        public global::Soenneker.N8n.OpenApiClient.Models.UpdateDataTableRowsRequestFilterFiltersItemConditionAnyOf2? UpdateDataTableRowsRequestFilterFiltersItemConditionAnyOf2 { get; set; }
        /// <summary>Composed type representation for type <see cref="global::Soenneker.N8n.OpenApiClient.Models.UpdateDataTableRowsRequestFilterFiltersItemConditionAnyOf3"/></summary>
        public global::Soenneker.N8n.OpenApiClient.Models.UpdateDataTableRowsRequestFilterFiltersItemConditionAnyOf3? UpdateDataTableRowsRequestFilterFiltersItemConditionAnyOf3 { get; set; }
        /// <summary>Composed type representation for type <see cref="global::Soenneker.N8n.OpenApiClient.Models.UpdateDataTableRowsRequestFilterFiltersItemConditionAnyOf4"/></summary>
        public global::Soenneker.N8n.OpenApiClient.Models.UpdateDataTableRowsRequestFilterFiltersItemConditionAnyOf4? UpdateDataTableRowsRequestFilterFiltersItemConditionAnyOf4 { get; set; }
        /// <summary>Composed type representation for type <see cref="global::Soenneker.N8n.OpenApiClient.Models.UpdateDataTableRowsRequestFilterFiltersItemConditionAnyOf5"/></summary>
        public global::Soenneker.N8n.OpenApiClient.Models.UpdateDataTableRowsRequestFilterFiltersItemConditionAnyOf5? UpdateDataTableRowsRequestFilterFiltersItemConditionAnyOf5 { get; set; }
        /// <summary>Composed type representation for type <see cref="global::Soenneker.N8n.OpenApiClient.Models.UpdateDataTableRowsRequestFilterFiltersItemConditionAnyOf6"/></summary>
        public global::Soenneker.N8n.OpenApiClient.Models.UpdateDataTableRowsRequestFilterFiltersItemConditionAnyOf6? UpdateDataTableRowsRequestFilterFiltersItemConditionAnyOf6 { get; set; }
        /// <summary>Composed type representation for type <see cref="global::Soenneker.N8n.OpenApiClient.Models.UpdateDataTableRowsRequestFilterFiltersItemConditionAnyOf7"/></summary>
        public global::Soenneker.N8n.OpenApiClient.Models.UpdateDataTableRowsRequestFilterFiltersItemConditionAnyOf7? UpdateDataTableRowsRequestFilterFiltersItemConditionAnyOf7 { get; set; }
        /// <summary>Composed type representation for type <see cref="global::Soenneker.N8n.OpenApiClient.Models.UpdateDataTableRowsRequestFilterFiltersItemConditionAnyOf8"/></summary>
        public global::Soenneker.N8n.OpenApiClient.Models.UpdateDataTableRowsRequestFilterFiltersItemConditionAnyOf8? UpdateDataTableRowsRequestFilterFiltersItemConditionAnyOf8 { get; set; }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.N8n.OpenApiClient.Models.UpdateDataTableRowsRequestFilterFiltersItemCondition"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.N8n.OpenApiClient.Models.UpdateDataTableRowsRequestFilterFiltersItemCondition CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            var result = new global::Soenneker.N8n.OpenApiClient.Models.UpdateDataTableRowsRequestFilterFiltersItemCondition();
            if(parseNode.GetEnumValue<global::Soenneker.N8n.OpenApiClient.Models.UpdateDataTableRowsRequestFilterFiltersItemConditionAnyOf1>() is global::Soenneker.N8n.OpenApiClient.Models.UpdateDataTableRowsRequestFilterFiltersItemConditionAnyOf1 updateDataTableRowsRequestFilterFiltersItemConditionAnyOf1Value)
            {
                result.UpdateDataTableRowsRequestFilterFiltersItemConditionAnyOf1 = updateDataTableRowsRequestFilterFiltersItemConditionAnyOf1Value;
            }
            else if(parseNode.GetEnumValue<global::Soenneker.N8n.OpenApiClient.Models.UpdateDataTableRowsRequestFilterFiltersItemConditionAnyOf2>() is global::Soenneker.N8n.OpenApiClient.Models.UpdateDataTableRowsRequestFilterFiltersItemConditionAnyOf2 updateDataTableRowsRequestFilterFiltersItemConditionAnyOf2Value)
            {
                result.UpdateDataTableRowsRequestFilterFiltersItemConditionAnyOf2 = updateDataTableRowsRequestFilterFiltersItemConditionAnyOf2Value;
            }
            else if(parseNode.GetEnumValue<global::Soenneker.N8n.OpenApiClient.Models.UpdateDataTableRowsRequestFilterFiltersItemConditionAnyOf3>() is global::Soenneker.N8n.OpenApiClient.Models.UpdateDataTableRowsRequestFilterFiltersItemConditionAnyOf3 updateDataTableRowsRequestFilterFiltersItemConditionAnyOf3Value)
            {
                result.UpdateDataTableRowsRequestFilterFiltersItemConditionAnyOf3 = updateDataTableRowsRequestFilterFiltersItemConditionAnyOf3Value;
            }
            else if(parseNode.GetEnumValue<global::Soenneker.N8n.OpenApiClient.Models.UpdateDataTableRowsRequestFilterFiltersItemConditionAnyOf4>() is global::Soenneker.N8n.OpenApiClient.Models.UpdateDataTableRowsRequestFilterFiltersItemConditionAnyOf4 updateDataTableRowsRequestFilterFiltersItemConditionAnyOf4Value)
            {
                result.UpdateDataTableRowsRequestFilterFiltersItemConditionAnyOf4 = updateDataTableRowsRequestFilterFiltersItemConditionAnyOf4Value;
            }
            else if(parseNode.GetEnumValue<global::Soenneker.N8n.OpenApiClient.Models.UpdateDataTableRowsRequestFilterFiltersItemConditionAnyOf5>() is global::Soenneker.N8n.OpenApiClient.Models.UpdateDataTableRowsRequestFilterFiltersItemConditionAnyOf5 updateDataTableRowsRequestFilterFiltersItemConditionAnyOf5Value)
            {
                result.UpdateDataTableRowsRequestFilterFiltersItemConditionAnyOf5 = updateDataTableRowsRequestFilterFiltersItemConditionAnyOf5Value;
            }
            else if(parseNode.GetEnumValue<global::Soenneker.N8n.OpenApiClient.Models.UpdateDataTableRowsRequestFilterFiltersItemConditionAnyOf6>() is global::Soenneker.N8n.OpenApiClient.Models.UpdateDataTableRowsRequestFilterFiltersItemConditionAnyOf6 updateDataTableRowsRequestFilterFiltersItemConditionAnyOf6Value)
            {
                result.UpdateDataTableRowsRequestFilterFiltersItemConditionAnyOf6 = updateDataTableRowsRequestFilterFiltersItemConditionAnyOf6Value;
            }
            else if(parseNode.GetEnumValue<global::Soenneker.N8n.OpenApiClient.Models.UpdateDataTableRowsRequestFilterFiltersItemConditionAnyOf7>() is global::Soenneker.N8n.OpenApiClient.Models.UpdateDataTableRowsRequestFilterFiltersItemConditionAnyOf7 updateDataTableRowsRequestFilterFiltersItemConditionAnyOf7Value)
            {
                result.UpdateDataTableRowsRequestFilterFiltersItemConditionAnyOf7 = updateDataTableRowsRequestFilterFiltersItemConditionAnyOf7Value;
            }
            else if(parseNode.GetEnumValue<global::Soenneker.N8n.OpenApiClient.Models.UpdateDataTableRowsRequestFilterFiltersItemConditionAnyOf8>() is global::Soenneker.N8n.OpenApiClient.Models.UpdateDataTableRowsRequestFilterFiltersItemConditionAnyOf8 updateDataTableRowsRequestFilterFiltersItemConditionAnyOf8Value)
            {
                result.UpdateDataTableRowsRequestFilterFiltersItemConditionAnyOf8 = updateDataTableRowsRequestFilterFiltersItemConditionAnyOf8Value;
            }
            return result;
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>();
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            if(UpdateDataTableRowsRequestFilterFiltersItemConditionAnyOf1 != null)
            {
                writer.WriteEnumValue<global::Soenneker.N8n.OpenApiClient.Models.UpdateDataTableRowsRequestFilterFiltersItemConditionAnyOf1>(null, UpdateDataTableRowsRequestFilterFiltersItemConditionAnyOf1);
            }
            else if(UpdateDataTableRowsRequestFilterFiltersItemConditionAnyOf2 != null)
            {
                writer.WriteEnumValue<global::Soenneker.N8n.OpenApiClient.Models.UpdateDataTableRowsRequestFilterFiltersItemConditionAnyOf2>(null, UpdateDataTableRowsRequestFilterFiltersItemConditionAnyOf2);
            }
            else if(UpdateDataTableRowsRequestFilterFiltersItemConditionAnyOf3 != null)
            {
                writer.WriteEnumValue<global::Soenneker.N8n.OpenApiClient.Models.UpdateDataTableRowsRequestFilterFiltersItemConditionAnyOf3>(null, UpdateDataTableRowsRequestFilterFiltersItemConditionAnyOf3);
            }
            else if(UpdateDataTableRowsRequestFilterFiltersItemConditionAnyOf4 != null)
            {
                writer.WriteEnumValue<global::Soenneker.N8n.OpenApiClient.Models.UpdateDataTableRowsRequestFilterFiltersItemConditionAnyOf4>(null, UpdateDataTableRowsRequestFilterFiltersItemConditionAnyOf4);
            }
            else if(UpdateDataTableRowsRequestFilterFiltersItemConditionAnyOf5 != null)
            {
                writer.WriteEnumValue<global::Soenneker.N8n.OpenApiClient.Models.UpdateDataTableRowsRequestFilterFiltersItemConditionAnyOf5>(null, UpdateDataTableRowsRequestFilterFiltersItemConditionAnyOf5);
            }
            else if(UpdateDataTableRowsRequestFilterFiltersItemConditionAnyOf6 != null)
            {
                writer.WriteEnumValue<global::Soenneker.N8n.OpenApiClient.Models.UpdateDataTableRowsRequestFilterFiltersItemConditionAnyOf6>(null, UpdateDataTableRowsRequestFilterFiltersItemConditionAnyOf6);
            }
            else if(UpdateDataTableRowsRequestFilterFiltersItemConditionAnyOf7 != null)
            {
                writer.WriteEnumValue<global::Soenneker.N8n.OpenApiClient.Models.UpdateDataTableRowsRequestFilterFiltersItemConditionAnyOf7>(null, UpdateDataTableRowsRequestFilterFiltersItemConditionAnyOf7);
            }
            else if(UpdateDataTableRowsRequestFilterFiltersItemConditionAnyOf8 != null)
            {
                writer.WriteEnumValue<global::Soenneker.N8n.OpenApiClient.Models.UpdateDataTableRowsRequestFilterFiltersItemConditionAnyOf8>(null, UpdateDataTableRowsRequestFilterFiltersItemConditionAnyOf8);
            }
        }
    }
}
#pragma warning restore CS0618
