// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.N8n.OpenApiClient.Models
{
    /// <summary>Controls which workflows are allowed to call this workflow using the Execute Workflow node. Defaults to workflowsFromSameOwner.Available options:- `any`: Any workflow can call this workflow (no restrictions)- `none`: No other workflows can call this workflow (completely blocked)- `workflowsFromSameOwner` (default): Only workflows owned by the same project can call this workflow- `workflowsFromAList`: Only the workflows listed in `callerIds` can call this workflow</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum UpdateWorkflowRequestSettingsCallerPolicy
    {
        [EnumMember(Value = "any")]
        #pragma warning disable CS1591
        Any,
        #pragma warning restore CS1591
        [EnumMember(Value = "none")]
        #pragma warning disable CS1591
        None,
        #pragma warning restore CS1591
        [EnumMember(Value = "workflowsFromAList")]
        #pragma warning disable CS1591
        WorkflowsFromAList,
        #pragma warning restore CS1591
        [EnumMember(Value = "workflowsFromSameOwner")]
        #pragma warning disable CS1591
        WorkflowsFromSameOwner,
        #pragma warning restore CS1591
    }
}
