// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.N8n.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum UpdateRowsRequest_filter_filters_condition
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "eq")]
        #pragma warning disable CS1591
        Eq,
        #pragma warning restore CS1591
        [EnumMember(Value = "neq")]
        #pragma warning disable CS1591
        Neq,
        #pragma warning restore CS1591
        [EnumMember(Value = "like")]
        #pragma warning disable CS1591
        Like,
        #pragma warning restore CS1591
        [EnumMember(Value = "ilike")]
        #pragma warning disable CS1591
        Ilike,
        #pragma warning restore CS1591
        [EnumMember(Value = "gt")]
        #pragma warning disable CS1591
        Gt,
        #pragma warning restore CS1591
        [EnumMember(Value = "gte")]
        #pragma warning disable CS1591
        Gte,
        #pragma warning restore CS1591
        [EnumMember(Value = "lt")]
        #pragma warning disable CS1591
        Lt,
        #pragma warning restore CS1591
        [EnumMember(Value = "lte")]
        #pragma warning disable CS1591
        Lte,
        #pragma warning restore CS1591
    }
}
