// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.N8n.OpenApiClient.Models
{
    /// <summary>
    /// Filter conditions to match rows for update
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class UpdateRowsRequest_filter : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The filters property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.N8n.OpenApiClient.Models.UpdateRowsRequest_filter_filters>? Filters { get; set; }
#nullable restore
#else
        public List<global::Soenneker.N8n.OpenApiClient.Models.UpdateRowsRequest_filter_filters> Filters { get; set; }
#endif
        /// <summary>The type property</summary>
        public global::Soenneker.N8n.OpenApiClient.Models.UpdateRowsRequest_filter_type? Type { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.N8n.OpenApiClient.Models.UpdateRowsRequest_filter"/> and sets the default values.
        /// </summary>
        public UpdateRowsRequest_filter()
        {
            AdditionalData = new Dictionary<string, object>();
            Type = global::Soenneker.N8n.OpenApiClient.Models.UpdateRowsRequest_filter_type.And;
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.N8n.OpenApiClient.Models.UpdateRowsRequest_filter"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.N8n.OpenApiClient.Models.UpdateRowsRequest_filter CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.N8n.OpenApiClient.Models.UpdateRowsRequest_filter();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "filters", n => { Filters = n.GetCollectionOfObjectValues<global::Soenneker.N8n.OpenApiClient.Models.UpdateRowsRequest_filter_filters>(global::Soenneker.N8n.OpenApiClient.Models.UpdateRowsRequest_filter_filters.CreateFromDiscriminatorValue)?.AsList(); } },
                { "type", n => { Type = n.GetEnumValue<global::Soenneker.N8n.OpenApiClient.Models.UpdateRowsRequest_filter_type>(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteCollectionOfObjectValues<global::Soenneker.N8n.OpenApiClient.Models.UpdateRowsRequest_filter_filters>("filters", Filters);
            writer.WriteEnumValue<global::Soenneker.N8n.OpenApiClient.Models.UpdateRowsRequest_filter_type>("type", Type);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
