// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.N8n.OpenApiClient.Models
{
    /// <summary>
    /// Composed type wrapper for classes <see cref="bool"/>, List&lt;global::Soenneker.N8n.OpenApiClient.Models.UpsertDataTableRow200ResponseAnyOf2Item&gt;, List&lt;global::Soenneker.N8n.OpenApiClient.Models.UpsertDataTableRow200ResponseAnyOf3Item&gt;
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class UpsertDataTableRow200Response : IComposedTypeWrapper, IParsable
    {
        /// <summary>Composed type representation for type <see cref="bool"/></summary>
        public bool? Boolean { get; set; }
        /// <summary>Composed type representation for type List&lt;global::Soenneker.N8n.OpenApiClient.Models.UpsertDataTableRow200ResponseAnyOf2Item&gt;</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.N8n.OpenApiClient.Models.UpsertDataTableRow200ResponseAnyOf2Item>? UpsertDataTableRow200ResponseAnyOf2Item { get; set; }
#nullable restore
#else
        public List<global::Soenneker.N8n.OpenApiClient.Models.UpsertDataTableRow200ResponseAnyOf2Item> UpsertDataTableRow200ResponseAnyOf2Item { get; set; }
#endif
        /// <summary>Composed type representation for type List&lt;global::Soenneker.N8n.OpenApiClient.Models.UpsertDataTableRow200ResponseAnyOf3Item&gt;</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.N8n.OpenApiClient.Models.UpsertDataTableRow200ResponseAnyOf3Item>? UpsertDataTableRow200ResponseAnyOf3Item { get; set; }
#nullable restore
#else
        public List<global::Soenneker.N8n.OpenApiClient.Models.UpsertDataTableRow200ResponseAnyOf3Item> UpsertDataTableRow200ResponseAnyOf3Item { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.N8n.OpenApiClient.Models.UpsertDataTableRow200Response"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.N8n.OpenApiClient.Models.UpsertDataTableRow200Response CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            var result = new global::Soenneker.N8n.OpenApiClient.Models.UpsertDataTableRow200Response();
            if(parseNode.GetBoolValue() is bool booleanValue)
            {
                result.Boolean = booleanValue;
            }
            else if(parseNode.GetCollectionOfObjectValues<global::Soenneker.N8n.OpenApiClient.Models.UpsertDataTableRow200ResponseAnyOf2Item>(global::Soenneker.N8n.OpenApiClient.Models.UpsertDataTableRow200ResponseAnyOf2Item.CreateFromDiscriminatorValue)?.AsList() is List<global::Soenneker.N8n.OpenApiClient.Models.UpsertDataTableRow200ResponseAnyOf2Item> upsertDataTableRow200ResponseAnyOf2ItemValue)
            {
                result.UpsertDataTableRow200ResponseAnyOf2Item = upsertDataTableRow200ResponseAnyOf2ItemValue;
            }
            else if(parseNode.GetCollectionOfObjectValues<global::Soenneker.N8n.OpenApiClient.Models.UpsertDataTableRow200ResponseAnyOf3Item>(global::Soenneker.N8n.OpenApiClient.Models.UpsertDataTableRow200ResponseAnyOf3Item.CreateFromDiscriminatorValue)?.AsList() is List<global::Soenneker.N8n.OpenApiClient.Models.UpsertDataTableRow200ResponseAnyOf3Item> upsertDataTableRow200ResponseAnyOf3ItemValue)
            {
                result.UpsertDataTableRow200ResponseAnyOf3Item = upsertDataTableRow200ResponseAnyOf3ItemValue;
            }
            return result;
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>();
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            if(Boolean != null)
            {
                writer.WriteBoolValue(null, Boolean);
            }
            else if(UpsertDataTableRow200ResponseAnyOf2Item != null)
            {
                writer.WriteCollectionOfObjectValues<global::Soenneker.N8n.OpenApiClient.Models.UpsertDataTableRow200ResponseAnyOf2Item>(null, UpsertDataTableRow200ResponseAnyOf2Item);
            }
            else if(UpsertDataTableRow200ResponseAnyOf3Item != null)
            {
                writer.WriteCollectionOfObjectValues<global::Soenneker.N8n.OpenApiClient.Models.UpsertDataTableRow200ResponseAnyOf3Item>(null, UpsertDataTableRow200ResponseAnyOf3Item);
            }
        }
    }
}
#pragma warning restore CS0618
