// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.N8n.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class UpsertRowRequest : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Column values for the row</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.N8n.OpenApiClient.Models.UpsertRowRequest_data? Data { get; set; }
#nullable restore
#else
        public global::Soenneker.N8n.OpenApiClient.Models.UpsertRowRequest_data Data { get; set; }
#endif
        /// <summary>If true, preview changes without persisting them</summary>
        public bool? DryRun { get; set; }
        /// <summary>Filter conditions to match existing row. If no row matches, a new row is inserted.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.N8n.OpenApiClient.Models.UpsertRowRequest_filter? Filter { get; set; }
#nullable restore
#else
        public global::Soenneker.N8n.OpenApiClient.Models.UpsertRowRequest_filter Filter { get; set; }
#endif
        /// <summary>If true, return the upserted row; if false, return true on success</summary>
        public bool? ReturnData { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.N8n.OpenApiClient.Models.UpsertRowRequest"/> and sets the default values.
        /// </summary>
        public UpsertRowRequest()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.N8n.OpenApiClient.Models.UpsertRowRequest"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.N8n.OpenApiClient.Models.UpsertRowRequest CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.N8n.OpenApiClient.Models.UpsertRowRequest();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "data", n => { Data = n.GetObjectValue<global::Soenneker.N8n.OpenApiClient.Models.UpsertRowRequest_data>(global::Soenneker.N8n.OpenApiClient.Models.UpsertRowRequest_data.CreateFromDiscriminatorValue); } },
                { "dryRun", n => { DryRun = n.GetBoolValue(); } },
                { "filter", n => { Filter = n.GetObjectValue<global::Soenneker.N8n.OpenApiClient.Models.UpsertRowRequest_filter>(global::Soenneker.N8n.OpenApiClient.Models.UpsertRowRequest_filter.CreateFromDiscriminatorValue); } },
                { "returnData", n => { ReturnData = n.GetBoolValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Soenneker.N8n.OpenApiClient.Models.UpsertRowRequest_data>("data", Data);
            writer.WriteBoolValue("dryRun", DryRun);
            writer.WriteObjectValue<global::Soenneker.N8n.OpenApiClient.Models.UpsertRowRequest_filter>("filter", Filter);
            writer.WriteBoolValue("returnData", ReturnData);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
