// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.N8n.OpenApiClient.Models
{
    /// <summary>
    /// Composed type wrapper for classes <see cref="global::Soenneker.N8n.OpenApiClient.Models.UpsertDataTableRowRequestFilterFiltersItemValueBranch1"/>, <see cref="global::Soenneker.N8n.OpenApiClient.Models.UpsertDataTableRowRequestFilterFiltersItemValueBranch2"/>, <see cref="global::Soenneker.N8n.OpenApiClient.Models.UpsertDataTableRowRequestFilterFiltersItemValueBranch3"/>, <see cref="global::Soenneker.N8n.OpenApiClient.Models.UpsertDataTableRowRequestFilterFiltersItemValueBranch4"/>, <see cref="global::Soenneker.N8n.OpenApiClient.Models.UpsertDataTableRowRequestFilterFiltersItemValueMember1"/>, <see cref="global::Soenneker.N8n.OpenApiClient.Models.UpsertDataTableRowRequestFilterFiltersItemValueMember2"/>
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class UpsertDataTableRowRequestFilterFiltersItemValue : IComposedTypeWrapper, IParsable
    {
        /// <summary>Composed type representation for type <see cref="global::Soenneker.N8n.OpenApiClient.Models.UpsertDataTableRowRequestFilterFiltersItemValueBranch1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.N8n.OpenApiClient.Models.UpsertDataTableRowRequestFilterFiltersItemValueBranch1? UpsertDataTableRowRequestFilterFiltersItemValueBranch1 { get; set; }
#nullable restore
#else
        public global::Soenneker.N8n.OpenApiClient.Models.UpsertDataTableRowRequestFilterFiltersItemValueBranch1 UpsertDataTableRowRequestFilterFiltersItemValueBranch1 { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.N8n.OpenApiClient.Models.UpsertDataTableRowRequestFilterFiltersItemValueBranch2"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.N8n.OpenApiClient.Models.UpsertDataTableRowRequestFilterFiltersItemValueBranch2? UpsertDataTableRowRequestFilterFiltersItemValueBranch2 { get; set; }
#nullable restore
#else
        public global::Soenneker.N8n.OpenApiClient.Models.UpsertDataTableRowRequestFilterFiltersItemValueBranch2 UpsertDataTableRowRequestFilterFiltersItemValueBranch2 { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.N8n.OpenApiClient.Models.UpsertDataTableRowRequestFilterFiltersItemValueBranch3"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.N8n.OpenApiClient.Models.UpsertDataTableRowRequestFilterFiltersItemValueBranch3? UpsertDataTableRowRequestFilterFiltersItemValueBranch3 { get; set; }
#nullable restore
#else
        public global::Soenneker.N8n.OpenApiClient.Models.UpsertDataTableRowRequestFilterFiltersItemValueBranch3 UpsertDataTableRowRequestFilterFiltersItemValueBranch3 { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.N8n.OpenApiClient.Models.UpsertDataTableRowRequestFilterFiltersItemValueBranch4"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.N8n.OpenApiClient.Models.UpsertDataTableRowRequestFilterFiltersItemValueBranch4? UpsertDataTableRowRequestFilterFiltersItemValueBranch4 { get; set; }
#nullable restore
#else
        public global::Soenneker.N8n.OpenApiClient.Models.UpsertDataTableRowRequestFilterFiltersItemValueBranch4 UpsertDataTableRowRequestFilterFiltersItemValueBranch4 { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.N8n.OpenApiClient.Models.UpsertDataTableRowRequestFilterFiltersItemValueMember1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.N8n.OpenApiClient.Models.UpsertDataTableRowRequestFilterFiltersItemValueMember1? UpsertDataTableRowRequestFilterFiltersItemValueMember1 { get; set; }
#nullable restore
#else
        public global::Soenneker.N8n.OpenApiClient.Models.UpsertDataTableRowRequestFilterFiltersItemValueMember1 UpsertDataTableRowRequestFilterFiltersItemValueMember1 { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.N8n.OpenApiClient.Models.UpsertDataTableRowRequestFilterFiltersItemValueMember2"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.N8n.OpenApiClient.Models.UpsertDataTableRowRequestFilterFiltersItemValueMember2? UpsertDataTableRowRequestFilterFiltersItemValueMember2 { get; set; }
#nullable restore
#else
        public global::Soenneker.N8n.OpenApiClient.Models.UpsertDataTableRowRequestFilterFiltersItemValueMember2 UpsertDataTableRowRequestFilterFiltersItemValueMember2 { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.N8n.OpenApiClient.Models.UpsertDataTableRowRequestFilterFiltersItemValue"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.N8n.OpenApiClient.Models.UpsertDataTableRowRequestFilterFiltersItemValue CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            var result = new global::Soenneker.N8n.OpenApiClient.Models.UpsertDataTableRowRequestFilterFiltersItemValue();
            result.UpsertDataTableRowRequestFilterFiltersItemValueBranch1 = new global::Soenneker.N8n.OpenApiClient.Models.UpsertDataTableRowRequestFilterFiltersItemValueBranch1();
            result.UpsertDataTableRowRequestFilterFiltersItemValueBranch2 = new global::Soenneker.N8n.OpenApiClient.Models.UpsertDataTableRowRequestFilterFiltersItemValueBranch2();
            result.UpsertDataTableRowRequestFilterFiltersItemValueBranch3 = new global::Soenneker.N8n.OpenApiClient.Models.UpsertDataTableRowRequestFilterFiltersItemValueBranch3();
            result.UpsertDataTableRowRequestFilterFiltersItemValueBranch4 = new global::Soenneker.N8n.OpenApiClient.Models.UpsertDataTableRowRequestFilterFiltersItemValueBranch4();
            result.UpsertDataTableRowRequestFilterFiltersItemValueMember1 = new global::Soenneker.N8n.OpenApiClient.Models.UpsertDataTableRowRequestFilterFiltersItemValueMember1();
            result.UpsertDataTableRowRequestFilterFiltersItemValueMember2 = new global::Soenneker.N8n.OpenApiClient.Models.UpsertDataTableRowRequestFilterFiltersItemValueMember2();
            return result;
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            if(UpsertDataTableRowRequestFilterFiltersItemValueBranch1 != null || UpsertDataTableRowRequestFilterFiltersItemValueBranch2 != null || UpsertDataTableRowRequestFilterFiltersItemValueBranch3 != null || UpsertDataTableRowRequestFilterFiltersItemValueBranch4 != null || UpsertDataTableRowRequestFilterFiltersItemValueMember1 != null || UpsertDataTableRowRequestFilterFiltersItemValueMember2 != null)
            {
                return ParseNodeHelper.MergeDeserializersForIntersectionWrapper(UpsertDataTableRowRequestFilterFiltersItemValueBranch1, UpsertDataTableRowRequestFilterFiltersItemValueBranch2, UpsertDataTableRowRequestFilterFiltersItemValueBranch3, UpsertDataTableRowRequestFilterFiltersItemValueBranch4, UpsertDataTableRowRequestFilterFiltersItemValueMember1, UpsertDataTableRowRequestFilterFiltersItemValueMember2);
            }
            return new Dictionary<string, Action<IParseNode>>();
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Soenneker.N8n.OpenApiClient.Models.UpsertDataTableRowRequestFilterFiltersItemValueBranch1>(null, UpsertDataTableRowRequestFilterFiltersItemValueBranch1, UpsertDataTableRowRequestFilterFiltersItemValueBranch2, UpsertDataTableRowRequestFilterFiltersItemValueBranch3, UpsertDataTableRowRequestFilterFiltersItemValueBranch4, UpsertDataTableRowRequestFilterFiltersItemValueMember1, UpsertDataTableRowRequestFilterFiltersItemValueMember2);
        }
    }
}
#pragma warning restore CS0618
