// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.N8n.OpenApiClient.Models
{
    /// <summary>
    /// Composed type wrapper for classes <see cref="global::Soenneker.N8n.OpenApiClient.Models.WorkflowPublishPublicDtoGeneratedSettingsSaveManualExecutionsBranch1"/>, <see cref="global::Soenneker.N8n.OpenApiClient.Models.WorkflowPublishPublicDtoGeneratedSettingsSaveManualExecutionsWrapper"/>
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class WorkflowPublishPublicDtoGeneratedSettingsSaveManualExecutions : IComposedTypeWrapper, IParsable
    {
        /// <summary>Composed type representation for type <see cref="global::Soenneker.N8n.OpenApiClient.Models.WorkflowPublishPublicDtoGeneratedSettingsSaveManualExecutionsBranch1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.N8n.OpenApiClient.Models.WorkflowPublishPublicDtoGeneratedSettingsSaveManualExecutionsBranch1? WorkflowPublishPublicDtoGeneratedSettingsSaveManualExecutionsBranch1 { get; set; }
#nullable restore
#else
        public global::Soenneker.N8n.OpenApiClient.Models.WorkflowPublishPublicDtoGeneratedSettingsSaveManualExecutionsBranch1 WorkflowPublishPublicDtoGeneratedSettingsSaveManualExecutionsBranch1 { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.N8n.OpenApiClient.Models.WorkflowPublishPublicDtoGeneratedSettingsSaveManualExecutionsWrapper"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.N8n.OpenApiClient.Models.WorkflowPublishPublicDtoGeneratedSettingsSaveManualExecutionsWrapper? WorkflowPublishPublicDtoGeneratedSettingsSaveManualExecutionsWrapper { get; set; }
#nullable restore
#else
        public global::Soenneker.N8n.OpenApiClient.Models.WorkflowPublishPublicDtoGeneratedSettingsSaveManualExecutionsWrapper WorkflowPublishPublicDtoGeneratedSettingsSaveManualExecutionsWrapper { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.N8n.OpenApiClient.Models.WorkflowPublishPublicDtoGeneratedSettingsSaveManualExecutions"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.N8n.OpenApiClient.Models.WorkflowPublishPublicDtoGeneratedSettingsSaveManualExecutions CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            var mappingValue = parseNode.GetChildNode("")?.GetStringValue();
            var result = new global::Soenneker.N8n.OpenApiClient.Models.WorkflowPublishPublicDtoGeneratedSettingsSaveManualExecutions();
            if("WorkflowPublishPublicDtoGeneratedSettingsSaveManualExecutionsBranch1".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.WorkflowPublishPublicDtoGeneratedSettingsSaveManualExecutionsBranch1 = new global::Soenneker.N8n.OpenApiClient.Models.WorkflowPublishPublicDtoGeneratedSettingsSaveManualExecutionsBranch1();
            }
            else if("WorkflowPublishPublicDtoGeneratedSettingsSaveManualExecutionsWrapper".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.WorkflowPublishPublicDtoGeneratedSettingsSaveManualExecutionsWrapper = new global::Soenneker.N8n.OpenApiClient.Models.WorkflowPublishPublicDtoGeneratedSettingsSaveManualExecutionsWrapper();
            }
            return result;
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            if(WorkflowPublishPublicDtoGeneratedSettingsSaveManualExecutionsBranch1 != null)
            {
                return WorkflowPublishPublicDtoGeneratedSettingsSaveManualExecutionsBranch1.GetFieldDeserializers();
            }
            else if(WorkflowPublishPublicDtoGeneratedSettingsSaveManualExecutionsWrapper != null)
            {
                return WorkflowPublishPublicDtoGeneratedSettingsSaveManualExecutionsWrapper.GetFieldDeserializers();
            }
            return new Dictionary<string, Action<IParseNode>>();
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            if(WorkflowPublishPublicDtoGeneratedSettingsSaveManualExecutionsBranch1 != null)
            {
                writer.WriteObjectValue<global::Soenneker.N8n.OpenApiClient.Models.WorkflowPublishPublicDtoGeneratedSettingsSaveManualExecutionsBranch1>(null, WorkflowPublishPublicDtoGeneratedSettingsSaveManualExecutionsBranch1);
            }
            else if(WorkflowPublishPublicDtoGeneratedSettingsSaveManualExecutionsWrapper != null)
            {
                writer.WriteObjectValue<global::Soenneker.N8n.OpenApiClient.Models.WorkflowPublishPublicDtoGeneratedSettingsSaveManualExecutionsWrapper>(null, WorkflowPublishPublicDtoGeneratedSettingsSaveManualExecutionsWrapper);
            }
        }
    }
}
#pragma warning restore CS0618
