// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.N8n.OpenApiClient.Models
{
    /// <summary>Controls how binary data is resolved from a node&apos;s input. This is a derived, internal setting rather than something intended to be set programmatically. It is included in workflow responses for reference, but any value sent when creating or updating a workflow is ignored.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum WorkflowPublishPublicDtoGeneratedSettingsBinaryMode
    {
        [EnumMember(Value = "separate")]
        #pragma warning disable CS1591
        Separate,
        #pragma warning restore CS1591
        [EnumMember(Value = "combined")]
        #pragma warning disable CS1591
        Combined,
        #pragma warning restore CS1591
    }
}
