// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using Soenneker.N8n.OpenApiClient.Models;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Soenneker.N8n.OpenApiClient.N8nPackages.ImportSelection
{
    /// <summary>
    /// Builds and executes requests for operations under \n8n-packages\import-selection
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ImportSelectionRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.N8n.OpenApiClient.N8nPackages.ImportSelection.ImportSelectionRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ImportSelectionRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/n8n-packages/import-selection", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.N8n.OpenApiClient.N8nPackages.ImportSelection.ImportSelectionRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ImportSelectionRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/n8n-packages/import-selection", rawUrl)
        {
        }
        /// <summary>
        /// **Beta** — breaking changes may still occur without major version bump.Imports a chosen subset of workflows from one source project of a gzip-compressed tarpackage (`.n8np`), instead of the whole package. Send the archive as the multipart field`package`. The import is **additive** (cherry-pick): it never removes a workflow theselection omits. It creates or updates only the workflows named in `selectedWorkflowIds`,and deletes only the destination workflows named in `deletedWorkflowIds`.`selectedProjectId` names the single source project the selection is scoped to (its id as itappears in the package). The selected workflows are written into the instance project whose idmatches that source project, which is created if it does not yet exist; there is no separatetarget-project field. `selectedWorkflowIds` are source ids within that project; ids that belongto another project are dropped. `deletedWorkflowIds` are destination ids in the same project; anabsent id is a tolerated no-op, and a delete needs the `workflow:delete`scope. A delete id must not match the destination id of a selected workflow, includingwhen `workflowConflictPolicy=skip`. This overlap returns a 409 before any writes.The package must be a project package (a workflow package is rejected with a 400). Thecherry-pick conflict policies (folder, tag, and project) are fixed and are not accepted here;only `workflowConflictPolicy`, `workflowIdPolicy`, and `overwriteDeletionPolicy` areconfigurable. Maximum upload size is `N8N_ENDPOINTS_PAYLOAD_SIZE_MAX` MB (default 16). Thecaller is authorised through the `workflow:import` scope.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.N8n.OpenApiClient.Models.ImportResult"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Soenneker.N8n.OpenApiClient.Models.PostN8NPackagesImportSelection409Response">When receiving a 409 status code</exception>
        /// <exception cref="global::Soenneker.N8n.OpenApiClient.Models.PostN8NPackagesImportSelection422Response">When receiving a 422 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.N8n.OpenApiClient.Models.ImportResult?> PostAsync(MultipartBody body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.N8n.OpenApiClient.Models.ImportResult> PostAsync(MultipartBody body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPostRequestInformation(body, requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "409", global::Soenneker.N8n.OpenApiClient.Models.PostN8NPackagesImportSelection409Response.CreateFromDiscriminatorValue },
                { "422", global::Soenneker.N8n.OpenApiClient.Models.PostN8NPackagesImportSelection422Response.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Soenneker.N8n.OpenApiClient.Models.ImportResult>(requestInfo, global::Soenneker.N8n.OpenApiClient.Models.ImportResult.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// **Beta** — breaking changes may still occur without major version bump.Imports a chosen subset of workflows from one source project of a gzip-compressed tarpackage (`.n8np`), instead of the whole package. Send the archive as the multipart field`package`. The import is **additive** (cherry-pick): it never removes a workflow theselection omits. It creates or updates only the workflows named in `selectedWorkflowIds`,and deletes only the destination workflows named in `deletedWorkflowIds`.`selectedProjectId` names the single source project the selection is scoped to (its id as itappears in the package). The selected workflows are written into the instance project whose idmatches that source project, which is created if it does not yet exist; there is no separatetarget-project field. `selectedWorkflowIds` are source ids within that project; ids that belongto another project are dropped. `deletedWorkflowIds` are destination ids in the same project; anabsent id is a tolerated no-op, and a delete needs the `workflow:delete`scope. A delete id must not match the destination id of a selected workflow, includingwhen `workflowConflictPolicy=skip`. This overlap returns a 409 before any writes.The package must be a project package (a workflow package is rejected with a 400). Thecherry-pick conflict policies (folder, tag, and project) are fixed and are not accepted here;only `workflowConflictPolicy`, `workflowIdPolicy`, and `overwriteDeletionPolicy` areconfigurable. Maximum upload size is `N8N_ENDPOINTS_PAYLOAD_SIZE_MAX` MB (default 16). Thecaller is authorised through the `workflow:import` scope.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPostRequestInformation(MultipartBody body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPostRequestInformation(MultipartBody body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = new RequestInformation(Method.POST, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            requestInfo.SetContentFromParsable(RequestAdapter, "multipart/form-data", body);
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.N8n.OpenApiClient.N8nPackages.ImportSelection.ImportSelectionRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Soenneker.N8n.OpenApiClient.N8nPackages.ImportSelection.ImportSelectionRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Soenneker.N8n.OpenApiClient.N8nPackages.ImportSelection.ImportSelectionRequestBuilder(rawUrl, RequestAdapter);
        }
    }
}
#pragma warning restore CS0618
