// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.N8n.OpenApiClient.NodeTypePolicies.Projects.Item;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.N8n.OpenApiClient.NodeTypePolicies.Projects
{
    /// <summary>
    /// Builds and executes requests for operations under \node-type-policies\projects
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ProjectsRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the Soenneker.N8n.OpenApiClient.nodeTypePolicies.projects.item collection</summary>
        /// <param name="position">The ID of the project.</param>
        /// <returns>A <see cref="global::Soenneker.N8n.OpenApiClient.NodeTypePolicies.Projects.Item.WithProjectItemRequestBuilder"/></returns>
        public global::Soenneker.N8n.OpenApiClient.NodeTypePolicies.Projects.Item.WithProjectItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("projectId", position);
                return new global::Soenneker.N8n.OpenApiClient.NodeTypePolicies.Projects.Item.WithProjectItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.N8n.OpenApiClient.NodeTypePolicies.Projects.ProjectsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ProjectsRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/node-type-policies/projects", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.N8n.OpenApiClient.NodeTypePolicies.Projects.ProjectsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ProjectsRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/node-type-policies/projects", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
