// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.N8n.OpenApiClient.Executions.Stop
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class StopPostRequestBody : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Only stop executions that started after this time.</summary>
        public DateTimeOffset? StartedAfter { get; set; }
        /// <summary>Only stop executions that started before this time.</summary>
        public DateTimeOffset? StartedBefore { get; set; }
        /// <summary>Array of execution statuses to stop. Must include at least one status.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.N8n.OpenApiClient.Executions.Stop.StopPostRequestBody_status?>? Status { get; set; }
#nullable restore
#else
        public List<global::Soenneker.N8n.OpenApiClient.Executions.Stop.StopPostRequestBody_status?> Status { get; set; }
#endif
        /// <summary>Optional workflow ID to filter executions. If not provided, will stop executions across all accessible workflows.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? WorkflowId { get; set; }
#nullable restore
#else
        public string WorkflowId { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.N8n.OpenApiClient.Executions.Stop.StopPostRequestBody"/> and sets the default values.
        /// </summary>
        public StopPostRequestBody()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.N8n.OpenApiClient.Executions.Stop.StopPostRequestBody"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.N8n.OpenApiClient.Executions.Stop.StopPostRequestBody CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.N8n.OpenApiClient.Executions.Stop.StopPostRequestBody();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "startedAfter", n => { StartedAfter = n.GetDateTimeOffsetValue(); } },
                { "startedBefore", n => { StartedBefore = n.GetDateTimeOffsetValue(); } },
                { "status", n => { Status = n.GetCollectionOfEnumValues<global::Soenneker.N8n.OpenApiClient.Executions.Stop.StopPostRequestBody_status>()?.AsList(); } },
                { "workflowId", n => { WorkflowId = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteDateTimeOffsetValue("startedAfter", StartedAfter);
            writer.WriteDateTimeOffsetValue("startedBefore", StartedBefore);
            writer.WriteCollectionOfEnumValues<global::Soenneker.N8n.OpenApiClient.Executions.Stop.StopPostRequestBody_status>("status", Status);
            writer.WriteStringValue("workflowId", WorkflowId);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
