// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Soenneker.N8n.OpenApiClient.DataTables.Item.Rows.Delete
{
    /// <summary>
    /// Builds and executes requests for operations under \data-tables\{dataTableId}\rows\delete
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class DeleteRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.N8n.OpenApiClient.DataTables.Item.Rows.Delete.DeleteRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public DeleteRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/data-tables/{dataTableId}/rows/delete?filter={filter}{&dryRun*,returnData*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.N8n.OpenApiClient.DataTables.Item.Rows.Delete.DeleteRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public DeleteRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/data-tables/{dataTableId}/rows/delete?filter={filter}{&dryRun*,returnData*}", rawUrl)
        {
        }
        /// <summary>
        /// Delete rows matching filter conditions from a data table. Filter is required to prevent accidental deletion of all data.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.N8n.OpenApiClient.DataTables.Item.Rows.Delete.DeleteRequestBuilder.DeleteDeleteResponse"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.N8n.OpenApiClient.DataTables.Item.Rows.Delete.DeleteRequestBuilder.DeleteDeleteResponse?> DeleteAsync(Action<RequestConfiguration<global::Soenneker.N8n.OpenApiClient.DataTables.Item.Rows.Delete.DeleteRequestBuilder.DeleteRequestBuilderDeleteQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.N8n.OpenApiClient.DataTables.Item.Rows.Delete.DeleteRequestBuilder.DeleteDeleteResponse> DeleteAsync(Action<RequestConfiguration<global::Soenneker.N8n.OpenApiClient.DataTables.Item.Rows.Delete.DeleteRequestBuilder.DeleteRequestBuilderDeleteQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToDeleteRequestInformation(requestConfiguration);
            return await RequestAdapter.SendAsync<global::Soenneker.N8n.OpenApiClient.DataTables.Item.Rows.Delete.DeleteRequestBuilder.DeleteDeleteResponse>(requestInfo, global::Soenneker.N8n.OpenApiClient.DataTables.Item.Rows.Delete.DeleteRequestBuilder.DeleteDeleteResponse.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Delete rows matching filter conditions from a data table. Filter is required to prevent accidental deletion of all data.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToDeleteRequestInformation(Action<RequestConfiguration<global::Soenneker.N8n.OpenApiClient.DataTables.Item.Rows.Delete.DeleteRequestBuilder.DeleteRequestBuilderDeleteQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToDeleteRequestInformation(Action<RequestConfiguration<global::Soenneker.N8n.OpenApiClient.DataTables.Item.Rows.Delete.DeleteRequestBuilder.DeleteRequestBuilderDeleteQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.DELETE, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.N8n.OpenApiClient.DataTables.Item.Rows.Delete.DeleteRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Soenneker.N8n.OpenApiClient.DataTables.Item.Rows.Delete.DeleteRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Soenneker.N8n.OpenApiClient.DataTables.Item.Rows.Delete.DeleteRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="bool"/>, List&lt;global::Soenneker.N8n.OpenApiClient.DataTables.Item.Rows.Delete.DataTableRow&gt;
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class DeleteDeleteResponse : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="bool"/></summary>
            public bool? Boolean { get; set; }
            /// <summary>Composed type representation for type List&lt;global::Soenneker.N8n.OpenApiClient.DataTables.Item.Rows.Delete.DataTableRow&gt;</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public List<global::Soenneker.N8n.OpenApiClient.DataTables.Item.Rows.Delete.DataTableRow>? DataTableRow { get; set; }
#nullable restore
#else
            public List<global::Soenneker.N8n.OpenApiClient.DataTables.Item.Rows.Delete.DataTableRow> DataTableRow { get; set; }
#endif
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::Soenneker.N8n.OpenApiClient.DataTables.Item.Rows.Delete.DeleteRequestBuilder.DeleteDeleteResponse"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::Soenneker.N8n.OpenApiClient.DataTables.Item.Rows.Delete.DeleteRequestBuilder.DeleteDeleteResponse CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
                var mappingValue = parseNode.GetChildNode("")?.GetStringValue();
                var result = new global::Soenneker.N8n.OpenApiClient.DataTables.Item.Rows.Delete.DeleteRequestBuilder.DeleteDeleteResponse();
                if(parseNode.GetBoolValue() is bool booleanValue)
                {
                    result.Boolean = booleanValue;
                }
                else if(parseNode.GetCollectionOfObjectValues<global::Soenneker.N8n.OpenApiClient.DataTables.Item.Rows.Delete.DataTableRow>(global::Soenneker.N8n.OpenApiClient.DataTables.Item.Rows.Delete.DataTableRow.CreateFromDiscriminatorValue)?.AsList() is List<global::Soenneker.N8n.OpenApiClient.DataTables.Item.Rows.Delete.DataTableRow> dataTableRowValue)
                {
                    result.DataTableRow = dataTableRowValue;
                }
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
                if(Boolean != null)
                {
                    writer.WriteBoolValue(null, Boolean);
                }
                else if(DataTableRow != null)
                {
                    writer.WriteCollectionOfObjectValues<global::Soenneker.N8n.OpenApiClient.DataTables.Item.Rows.Delete.DataTableRow>(null, DataTableRow);
                }
            }
        }
        /// <summary>
        /// Delete rows matching filter conditions from a data table. Filter is required to prevent accidental deletion of all data.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class DeleteRequestBuilderDeleteQueryParameters 
        {
            /// <summary>If true, preview which rows would be deleted without actually deleting them</summary>
            [QueryParameter("dryRun")]
            public bool? DryRun { get; set; }
            /// <summary>JSON string of filter conditions. Required to prevent accidental deletion of all data.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("filter")]
            public string? Filter { get; set; }
#nullable restore
#else
            [QueryParameter("filter")]
            public string Filter { get; set; }
#endif
            /// <summary>If true, return the deleted rows; if false, return true on success</summary>
            [QueryParameter("returnData")]
            public bool? ReturnData { get; set; }
        }
    }
}
#pragma warning restore CS0618
