// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.N8n.OpenApiClient.Promotions.Connections;
using Soenneker.N8n.OpenApiClient.Promotions.Projects;
using Soenneker.N8n.OpenApiClient.Promotions.Providers;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.N8n.OpenApiClient.Promotions
{
    /// <summary>
    /// Builds and executes requests for operations under \promotions
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class PromotionsRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The connections property</summary>
        public global::Soenneker.N8n.OpenApiClient.Promotions.Connections.ConnectionsRequestBuilder Connections
        {
            get => new global::Soenneker.N8n.OpenApiClient.Promotions.Connections.ConnectionsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The projects property</summary>
        public global::Soenneker.N8n.OpenApiClient.Promotions.Projects.ProjectsRequestBuilder Projects
        {
            get => new global::Soenneker.N8n.OpenApiClient.Promotions.Projects.ProjectsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The providers property</summary>
        public global::Soenneker.N8n.OpenApiClient.Promotions.Providers.ProvidersRequestBuilder Providers
        {
            get => new global::Soenneker.N8n.OpenApiClient.Promotions.Providers.ProvidersRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.N8n.OpenApiClient.Promotions.PromotionsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public PromotionsRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/promotions", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.N8n.OpenApiClient.Promotions.PromotionsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public PromotionsRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/promotions", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
