// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using Soenneker.N8n.OpenApiClient.Executions.Item.Retry;
using Soenneker.N8n.OpenApiClient.Executions.Item.Stop;
using Soenneker.N8n.OpenApiClient.Executions.Item.Tags;
using Soenneker.N8n.OpenApiClient.Models;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Soenneker.N8n.OpenApiClient.Executions.Item
{
    /// <summary>
    /// Builds and executes requests for operations under \executions\{executionId}
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class WithExecutionItemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The retry property</summary>
        public global::Soenneker.N8n.OpenApiClient.Executions.Item.Retry.RetryRequestBuilder Retry
        {
            get => new global::Soenneker.N8n.OpenApiClient.Executions.Item.Retry.RetryRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The stop property</summary>
        public global::Soenneker.N8n.OpenApiClient.Executions.Item.Stop.StopRequestBuilder Stop
        {
            get => new global::Soenneker.N8n.OpenApiClient.Executions.Item.Stop.StopRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The tags property</summary>
        public global::Soenneker.N8n.OpenApiClient.Executions.Item.Tags.TagsRequestBuilder Tags
        {
            get => new global::Soenneker.N8n.OpenApiClient.Executions.Item.Tags.TagsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.N8n.OpenApiClient.Executions.Item.WithExecutionItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithExecutionItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/executions/{executionId}{?ignoreDataSizeLimit*,includeData*,redactExecutionData*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.N8n.OpenApiClient.Executions.Item.WithExecutionItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithExecutionItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/executions/{executionId}{?ignoreDataSizeLimit*,includeData*,redactExecutionData*}", rawUrl)
        {
        }
        /// <summary>
        /// Deletes an execution from your instance.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.N8n.OpenApiClient.Models.DeleteExecution200Response"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.N8n.OpenApiClient.Models.DeleteExecution200Response?> DeleteAsync(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.N8n.OpenApiClient.Models.DeleteExecution200Response> DeleteAsync(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToDeleteRequestInformation(requestConfiguration);
            return await RequestAdapter.SendAsync<global::Soenneker.N8n.OpenApiClient.Models.DeleteExecution200Response>(requestInfo, global::Soenneker.N8n.OpenApiClient.Models.DeleteExecution200Response.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Retrieve an execution from your instance.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.N8n.OpenApiClient.Models.GetExecution200Response"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.N8n.OpenApiClient.Models.GetExecution200Response?> GetAsync(Action<RequestConfiguration<global::Soenneker.N8n.OpenApiClient.Executions.Item.WithExecutionItemRequestBuilder.WithExecutionItemRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.N8n.OpenApiClient.Models.GetExecution200Response> GetAsync(Action<RequestConfiguration<global::Soenneker.N8n.OpenApiClient.Executions.Item.WithExecutionItemRequestBuilder.WithExecutionItemRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            return await RequestAdapter.SendAsync<global::Soenneker.N8n.OpenApiClient.Models.GetExecution200Response>(requestInfo, global::Soenneker.N8n.OpenApiClient.Models.GetExecution200Response.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Deletes an execution from your instance.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToDeleteRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToDeleteRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.DELETE, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Retrieve an execution from your instance.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Soenneker.N8n.OpenApiClient.Executions.Item.WithExecutionItemRequestBuilder.WithExecutionItemRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Soenneker.N8n.OpenApiClient.Executions.Item.WithExecutionItemRequestBuilder.WithExecutionItemRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.N8n.OpenApiClient.Executions.Item.WithExecutionItemRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Soenneker.N8n.OpenApiClient.Executions.Item.WithExecutionItemRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Soenneker.N8n.OpenApiClient.Executions.Item.WithExecutionItemRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Retrieve an execution from your instance.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class WithExecutionItemRequestBuilderGetQueryParameters 
        {
            #pragma warning disable CS1591
            [QueryParameter("ignoreDataSizeLimit")]
            public global::Soenneker.N8n.OpenApiClient.Models.GetExecutionIgnoreDataSizeLimitParameter? IgnoreDataSizeLimit { get; set; }
            #pragma warning restore CS1591
            #pragma warning disable CS1591
            [QueryParameter("includeData")]
            public global::Soenneker.N8n.OpenApiClient.Models.GetExecutionIncludeDataParameter? IncludeData { get; set; }
            #pragma warning restore CS1591
            #pragma warning disable CS1591
            [QueryParameter("redactExecutionData")]
            public global::Soenneker.N8n.OpenApiClient.Models.GetExecutionRedactExecutionDataParameter? RedactExecutionData { get; set; }
            #pragma warning restore CS1591
        }
    }
}
#pragma warning restore CS0618
