// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.N8n.OpenApiClient.Promotions.Projects.Item.Changes.Item;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.N8n.OpenApiClient.Promotions.Projects.Item.Changes
{
    /// <summary>
    /// Builds and executes requests for operations under \promotions\projects\{projectId}\changes
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ChangesRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the Soenneker.N8n.OpenApiClient.promotions.projects.item.changes.item collection</summary>
        /// <param name="position">The direction of the promotion: apply or promote.</param>
        /// <returns>A <see cref="global::Soenneker.N8n.OpenApiClient.Promotions.Projects.Item.Changes.Item.WithDirectionItemRequestBuilder"/></returns>
        public global::Soenneker.N8n.OpenApiClient.Promotions.Projects.Item.Changes.Item.WithDirectionItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("direction", position);
                return new global::Soenneker.N8n.OpenApiClient.Promotions.Projects.Item.Changes.Item.WithDirectionItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.N8n.OpenApiClient.Promotions.Projects.Item.Changes.ChangesRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ChangesRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/promotions/projects/{projectId}/changes", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.N8n.OpenApiClient.Promotions.Projects.Item.Changes.ChangesRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ChangesRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/promotions/projects/{projectId}/changes", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
