// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.N8n.OpenApiClient.Settings.LogStreaming.Destinations;
using Soenneker.N8n.OpenApiClient.Settings.LogStreaming.EventTypes;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.N8n.OpenApiClient.Settings.LogStreaming
{
    /// <summary>
    /// Builds and executes requests for operations under \settings\log-streaming
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class LogStreamingRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The destinations property</summary>
        public global::Soenneker.N8n.OpenApiClient.Settings.LogStreaming.Destinations.DestinationsRequestBuilder Destinations
        {
            get => new global::Soenneker.N8n.OpenApiClient.Settings.LogStreaming.Destinations.DestinationsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The eventTypes property</summary>
        public global::Soenneker.N8n.OpenApiClient.Settings.LogStreaming.EventTypes.EventTypesRequestBuilder EventTypes
        {
            get => new global::Soenneker.N8n.OpenApiClient.Settings.LogStreaming.EventTypes.EventTypesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.N8n.OpenApiClient.Settings.LogStreaming.LogStreamingRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public LogStreamingRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/settings/log-streaming", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.N8n.OpenApiClient.Settings.LogStreaming.LogStreamingRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public LogStreamingRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/settings/log-streaming", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
